import type { ProviderAwareReplayImportContractCapabilities } from './types.js';

export function getProviderAwareReplayImportContractCapabilities(): ProviderAwareReplayImportContractCapabilities {
  return {
    providerAwareReplayImportContracts: true,
    deterministicReplayImportContracts: true,
    fixtureDerivedReplayImportCandidates: true,
    replayImportManifests: true,
    replayImportSourceMetadata: true,
    replayImportCompatibilityContracts: true,
    replayImportGatePolicies: true,
    replayImportPlanContracts: true,
    replayImportRejectionContracts: true,
    replayImportNormalizationContracts: true,
    replayImportValidationContracts: true,
    replayImportIntegrityContracts: true,
    replayImportProvenanceContracts: true,
    replayImportScenarioLinkage: true,
    replayImportSnapshotLinkage: true,
    replayImportReliabilityLinkage: true,
    replayImportQualityLinkage: true,
    replayImportAuditReports: true,
    replayImportViewModels: true,
    replayImportApiContracts: true,
    replayImportSelectors: true,
    replayImportLiveImport: false,
    replayImportRuntimeImport: false,
    replayImportLiveIngestion: false,
    replayImportRuntimeIngestion: false,
    replayImportFilesystemImport: false,
    replayImportLiveNetworkAccess: false,
    replayImportRuntimeCollectors: false,
    replayImportSecretsRequired: false,
    replayImportApiKeyRequired: false,
    replayImportWriteMethods: false,
    replayImportWalletLogic: false,
    replayImportPrivateKeyHandling: false,
    replayImportSigning: false,
    replayImportTransactionSending: false,
    replayImportExecution: false,
    replayImportTradingSignals: false,
    replayImportRecommendations: false,
    replayImportInvestmentAdvice: false,
    replayImportRouteHandlers: false,
    replayImportRuntimeRequests: false,
    replayImportUiRendering: false,
    replayImportDomAccess: false,
    replayImportPersistence: false,
    replayImportFilesystemWrites: false,
    replayImportBackgroundJobs: false,
    replayImportScheduledJobs: false,
    replayImportRealOrders: false,
    replayImportRealFunds: false,
    replayImportRealPnL: false,
    replayImportProviderExpansion: false,
  };
}
