import type { ProviderAwareReplayImportContractCapabilities } from './types.js';

export function getProviderAwareReplayImportContractCapabilities(): ProviderAwareReplayImportContractCapabilities {
  return {
    providerAwareReplayImportContracts: true,
    deterministicHistoricalSnapshotFixtures: true,
    fixtureDerivedSnapshotManifests: true,
    readOnlySnapshotSourceMetadata: true,
    snapshotSchemaContracts: true,
    snapshotProvenanceContracts: true,
    snapshotNormalizationContracts: true,
    snapshotValidationContracts: true,
    snapshotFreshnessContracts: true,
    snapshotIntegrityContracts: true,
    snapshotImportPlanContracts: true,
    snapshotRejectionContracts: true,
    snapshotReplayLinkage: true,
    snapshotReliabilityLinkage: true,
    snapshotAuditReports: true,
    snapshotViewModels: true,
    snapshotApiContracts: true,
    snapshotSelectors: true,
    historicalSnapshotLiveIngestion: false,
    historicalSnapshotRuntimeIngestion: false,
    historicalSnapshotLiveNetworkAccess: false,
    historicalSnapshotRuntimeCollectors: false,
    historicalSnapshotSecretsRequired: false,
    historicalSnapshotApiKeyRequired: false,
    historicalSnapshotWriteMethods: false,
    historicalSnapshotWalletLogic: false,
    historicalSnapshotPrivateKeyHandling: false,
    historicalSnapshotSigning: false,
    historicalSnapshotTransactionSending: false,
    historicalSnapshotExecution: false,
    historicalSnapshotTradingSignals: false,
    historicalSnapshotRecommendations: false,
    historicalSnapshotInvestmentAdvice: false,
    historicalSnapshotRouteHandlers: false,
    historicalSnapshotRuntimeRequests: false,
    historicalSnapshotUiRendering: false,
    historicalSnapshotDomAccess: false,
    historicalSnapshotPersistence: false,
    historicalSnapshotFilesystemWrites: false,
    historicalSnapshotBackgroundJobs: false,
    historicalSnapshotScheduledJobs: false,
    historicalSnapshotRealOrders: false,
    historicalSnapshotRealFunds: false,
    historicalSnapshotRealPnL: false,
    historicalSnapshotProviderExpansion: false,
  };
}
