import type { ProviderAwareReplayScenarioCapabilities } from './types.js';

export function getProviderAwareReplayScenarioCapabilities(): ProviderAwareReplayScenarioCapabilities {
  return {
    providerAwareReplayScenarios: true,
    deterministicProviderAwareScenarioGeneration: true,
    fixtureDerivedProviderAwareScenarios: true,
    localOnlyProviderAwareReplay: true,
    readOnlyProviderAwareReplay: true,
    providerQualityImportModels: true,
    providerProvenanceReplayMapping: true,
    replayParityChecks: true,
    fixtureRegenerationContracts: true,
    providerObservationReplayReports: true,
    generatedLifecyclePreviews: true,
    replayExpectationModels: true,
    providerAwareReplayViewModels: true,
    providerAwareReplayApiContracts: true,
    providerAwareReplaySelectors: true,
    providerAwareReplayLiveData: false,
    providerAwareReplayNetworkAccess: false,
    providerAwareReplayRuntimeIngestion: false,
    providerAwareReplayFilesystemWrites: false,
    providerAwareReplayDownloads: false,
    providerAwareReplayPersistence: false,
    providerAwareReplayWalletLogic: false,
    providerAwareReplayPrivateKeyHandling: false,
    providerAwareReplaySigning: false,
    providerAwareReplayTransactionSending: false,
    providerAwareReplayExecution: false,
    providerAwareReplayTradingSignals: false,
    providerAwareReplayRecommendations: false,
    providerAwareReplayInvestmentAdvice: false,
    providerAwareReplayRouteHandlers: false,
    providerAwareReplayRuntimeRequests: false,
    providerAwareReplayUiRendering: false,
    providerAwareReplayDomAccess: false,
    providerAwareReplayBackgroundJobs: false,
    providerAwareReplayScheduledJobs: false,
    providerAwareReplayRealOrders: false,
    providerAwareReplayRealFunds: false,
    providerAwareReplayRealPnL: false,
    providerAwareReplayLiveStrategySelection: false,
    providerAwareReplayAutoExecution: false,
  };
}
