export const DASHBOARD_ADAPTER_ERROR_CODES = {
  INVALID_INPUT: 'DASHBOARD_ADAPTER_ERROR',
  UNSUPPORTED_ENDPOINT: 'DASHBOARD_UNSUPPORTED_ENDPOINT',
  EMPTY: 'DASHBOARD_EMPTY',
  LOADING: 'DASHBOARD_LOADING',
} as const;
