import type { SyntheticStrategyComparisonLabCapabilities } from './types.js';

export function getSyntheticStrategyComparisonLabCapabilities(): SyntheticStrategyComparisonLabCapabilities {
  return {
    syntheticStrategyComparisonLab: true,
    syntheticStrategyComparisonFixtures: true,
    deterministicSyntheticStrategyComparison: true,
    localOnlySyntheticStrategyComparison: true,
    readOnlySyntheticStrategyComparison: true,
    fixtureDerivedSyntheticStrategyComparison: true,
    hypotheticalSyntheticStrategyComparison: true,
    syntheticStrategyVariants: true,
    syntheticStrategyScenarioMatrix: true,
    syntheticStrategyComparisonRuns: true,
    syntheticStrategyScorecards: true,
    syntheticStrategySensitivityWarnings: true,
    syntheticStrategyComparisonAggregates: true,
    syntheticStrategyComparisonViewModels: true,
    syntheticStrategyComparisonApiContracts: true,
    syntheticStrategyComparisonSelectors: true,
    syntheticStrategyComparisonLiveData: false,
    syntheticStrategyComparisonNetworkAccess: false,
    syntheticStrategyComparisonRealProviders: false,
    syntheticStrategyComparisonProviderAdapters: false,
    syntheticStrategyComparisonSolanaRpc: false,
    syntheticStrategyComparisonWebSocketAccess: false,
    syntheticStrategyComparisonGeyserYellowstone: false,
    syntheticStrategyComparisonPumpFunIntegration: false,
    syntheticStrategyComparisonDexIntegration: false,
    syntheticStrategyComparisonJitoIntegration: false,
    syntheticStrategyComparisonPersistence: false,
    syntheticStrategyComparisonFilesystemWrites: false,
    syntheticStrategyComparisonDownloads: false,
    syntheticStrategyComparisonRouteHandlers: false,
    syntheticStrategyComparisonHttpServer: false,
    syntheticStrategyComparisonRuntimeRequests: false,
    syntheticStrategyComparisonUiRendering: false,
    syntheticStrategyComparisonDomAccess: false,
    syntheticStrategyComparisonBackgroundJobs: false,
    syntheticStrategyComparisonScheduledJobs: false,
    syntheticStrategyComparisonWalletLogic: false,
    syntheticStrategyComparisonPrivateKeyHandling: false,
    syntheticStrategyComparisonSigning: false,
    syntheticStrategyComparisonTransactionSending: false,
    syntheticStrategyComparisonExecution: false,
    syntheticStrategyComparisonTradingSignals: false,
    syntheticStrategyComparisonRecommendations: false,
    syntheticStrategyComparisonInvestmentAdvice: false,
    syntheticStrategyComparisonLiveExecution: false,
    syntheticStrategyComparisonStrategySelection: false,
    syntheticStrategyComparisonRealOrders: false,
    syntheticStrategyComparisonRealFunds: false,
    syntheticStrategyComparisonRealPnL: false,
  };
}
