/**
 * packages/dashboard-read-models/src/export-json.ts
 *
 * Phase 18 — DashboardReadModelBundle JSON export.
 *
 * Returns a deterministic, JSON-safe export.
 * No undefined, no functions, no circular refs, no secrets.
 * Stable key ordering.
 */

import type { DashboardReadModelBundle, DashboardReadModelExport } from './types.js';

/**
 * Exports a DashboardReadModelBundle as a deterministic JSON-safe object.
 * Analysis-only — no trade signals, no action labels.
 */
export function exportDashboardReadModelJson(bundle: DashboardReadModelBundle): DashboardReadModelExport {
  return {
    exportKind: 'dashboard_read_model_export',
    bundle: {
      bundleId: bundle.bundleId,
      overview: {
        overviewId: bundle.overview.overviewId,
        totalFindings: bundle.overview.totalFindings,
        severityCounts: { ...bundle.overview.severityCounts },
        panelsAvailable: [...bundle.overview.panelsAvailable].sort(),
        safetyStatus: bundle.overview.safetyStatus,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      replayPanel: {
        panelId: bundle.replayPanel.panelId,
        panelKind: 'replay_panel',
        findings: bundle.replayPanel.findings.map(f => ({
          findingId: f.findingId,
          severity: f.severity,
          title: f.title,
          description: f.description,
          fixtureOnly: true as const,
          liveData: false as const,
          safeToDisplay: true as const,
          analysisOnly: true as const,
          nonExecutable: true as const,
          readOnly: true as const,
        })),
        totalFindings: bundle.replayPanel.totalFindings,
        severityCounts: { ...bundle.replayPanel.severityCounts },
        summaryText: bundle.replayPanel.summaryText,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      strategyPanel: {
        panelId: bundle.strategyPanel.panelId,
        panelKind: 'strategy_panel',
        findings: bundle.strategyPanel.findings.map(f => ({
          findingId: f.findingId,
          severity: f.severity,
          title: f.title,
          description: f.description,
          fixtureOnly: true as const,
          liveData: false as const,
          safeToDisplay: true as const,
          analysisOnly: true as const,
          nonExecutable: true as const,
          readOnly: true as const,
        })),
        totalFindings: bundle.strategyPanel.totalFindings,
        severityCounts: { ...bundle.strategyPanel.severityCounts },
        summaryText: bundle.strategyPanel.summaryText,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      evaluationPanel: {
        panelId: bundle.evaluationPanel.panelId,
        panelKind: 'evaluation_panel',
        findings: bundle.evaluationPanel.findings.map(f => ({
          findingId: f.findingId,
          severity: f.severity,
          title: f.title,
          description: f.description,
          fixtureOnly: true as const,
          liveData: false as const,
          safeToDisplay: true as const,
          analysisOnly: true as const,
          nonExecutable: true as const,
          readOnly: true as const,
        })),
        totalFindings: bundle.evaluationPanel.totalFindings,
        severityCounts: { ...bundle.evaluationPanel.severityCounts },
        summaryText: bundle.evaluationPanel.summaryText,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      evidencePanel: {
        panelId: bundle.evidencePanel.panelId,
        panelKind: 'evidence_panel',
        findings: bundle.evidencePanel.findings.map(f => ({
          findingId: f.findingId,
          severity: f.severity,
          title: f.title,
          description: f.description,
          fixtureOnly: true as const,
          liveData: false as const,
          safeToDisplay: true as const,
          analysisOnly: true as const,
          nonExecutable: true as const,
          readOnly: true as const,
        })),
        totalFindings: bundle.evidencePanel.totalFindings,
        severityCounts: { ...bundle.evidencePanel.severityCounts },
        summaryText: bundle.evidencePanel.summaryText,
        evidenceLedgerId: bundle.evidencePanel.evidenceLedgerId,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      safetyPanel: {
        panelId: bundle.safetyPanel.panelId,
        panelKind: 'safety_panel',
        capabilities: { ...bundle.safetyPanel.capabilities },
        lockedCapabilityNames: [...bundle.safetyPanel.lockedCapabilityNames].sort(),
        safetyInvariantsSatisfied: bundle.safetyPanel.safetyInvariantsSatisfied,
        summaryText: bundle.safetyPanel.summaryText,
        fixtureOnly: true,
        liveData: false,
        safeToDisplay: true,
        analysisOnly: true,
        nonExecutable: true,
        readOnly: true,
      },
      fixtureOnly: true,
      liveData: false,
      safeToDisplay: true,
      analysisOnly: true,
      nonExecutable: true,
      readOnly: true,
    },
    fixtureOnly: true,
    liveData: false,
    safeToDisplay: true,
    analysisOnly: true,
    nonExecutable: true,
    readOnly: true,
  };
}
