import type { ControlledLiveSmokeHarnessCapabilities } from './types.js';

export function getControlledLiveSmokeHarnessCapabilities(): ControlledLiveSmokeHarnessCapabilities {
  return {
    controlledLiveSmokeHarness: true,
    deterministicSmokeHarnessFixtures: true,
    disabledByDefaultSmokePlans: true,
    manualEnableSmokePolicies: true,
    smokeGuardContracts: true,
    readOnlySmokeCheckContracts: true,
    smokeEligibilityModels: true,
    smokeEnvironmentContracts: true,
    smokeSecretDenialContracts: true,
    smokeResultFixtures: true,
    smokeSkipFixtures: true,
    smokeFailureTaxonomy: true,
    smokeCertificationReports: true,
    smokeReadinessViewModels: true,
    smokeApiContracts: true,
    smokeSelectors: true,
    smokeLiveNetworkDefault: false,
    smokeRunsInStandardCi: false,
    smokeScheduledRuns: false,
    smokeRuntimeMonitoring: false,
    smokeRuntimeCollectors: false,
    smokeSecretsRequired: false,
    smokeProviderExpansion: false,
    smokeWriteMethods: false,
    smokeWalletLogic: false,
    smokePrivateKeyHandling: false,
    smokeSigning: false,
    smokeTransactionSending: false,
    smokeExecution: false,
    smokeTradingSignals: false,
    smokeRecommendations: false,
    smokeInvestmentAdvice: false,
    smokeRouteHandlers: false,
    smokeRuntimeRequests: false,
    smokeUiRendering: false,
    smokeDomAccess: false,
    smokePersistence: false,
    smokeFilesystemWrites: false,
    smokeBackgroundJobs: false,
    smokeScheduledJobs: false,
    smokeRealOrders: false,
    smokeRealFunds: false,
    smokeRealPnL: false,
  };
}
