import type { FirstReadOnlyProviderAdapterCapabilities } from './types.js';

export function getFirstReadOnlyProviderAdapterCapabilities(): FirstReadOnlyProviderAdapterCapabilities {
  return {
    firstReadOnlyProviderAdapter: true,
    firstReadOnlyProviderAdapterFixtures: true,
    deterministicFirstReadOnlyProviderAdapter: true,
    localOnlyFirstReadOnlyProviderAdapter: true,
    offlineFixtureFirstReadOnlyProviderAdapter: true,
    readOnlyFirstProviderClientContract: true,
    firstReadOnlyProviderFrozenResponses: true,
    firstReadOnlyProviderResponseMappings: true,
    firstReadOnlyProviderErrorNormalization: true,
    firstReadOnlyProviderConformanceChecks: true,
    firstReadOnlyProviderHealthModels: true,
    firstReadOnlyProviderSmokeGuard: true,
    firstReadOnlyProviderAdapterReports: true,
    firstReadOnlyProviderAdapterViewModels: true,
    firstReadOnlyProviderAdapterApiContracts: true,
    firstReadOnlyProviderAdapterSelectors: true,
    firstReadOnlyProviderLiveDataDefault: false,
    firstReadOnlyProviderNetworkAccessDefault: false,
    firstReadOnlyProviderLiveSmokeDefault: false,
    firstReadOnlyProviderRealTrading: false,
    firstReadOnlyProviderWriteMethods: false,
    firstReadOnlyProviderProviderSdkRequired: false,
    firstReadOnlyProviderApiKeysRequiredByDefault: false,
    firstReadOnlyProviderSolanaWriteRpc: false,
    firstReadOnlyProviderWalletLogic: false,
    firstReadOnlyProviderPrivateKeyHandling: false,
    firstReadOnlyProviderSigning: false,
    firstReadOnlyProviderTransactionSending: false,
    firstReadOnlyProviderExecution: false,
    firstReadOnlyProviderTradingSignals: false,
    firstReadOnlyProviderRecommendations: false,
    firstReadOnlyProviderInvestmentAdvice: false,
    firstReadOnlyProviderRouteHandlers: false,
    firstReadOnlyProviderRuntimeRequests: false,
    firstReadOnlyProviderUiRendering: false,
    firstReadOnlyProviderDomAccess: false,
    firstReadOnlyProviderPersistence: false,
    firstReadOnlyProviderFilesystemWrites: false,
    firstReadOnlyProviderBackgroundJobs: false,
    firstReadOnlyProviderScheduledJobs: false,
    firstReadOnlyProviderRealOrders: false,
    firstReadOnlyProviderRealFunds: false,
    firstReadOnlyProviderRealPnL: false,
  };
}
