/**
 * Phase 59 — Risk Explanation and Evidence Models v1: capabilities.
 */

import type { RiskExplanationEvidenceCapabilities } from './types.js';

export function getRiskExplanationEvidenceCapabilities(): RiskExplanationEvidenceCapabilities {
  return {
    riskExplanationEvidenceModels: true,
    riskExplanationEvidenceFixtures: true,
    deterministicRiskExplanationEvidence: true,
    localOnlyRiskExplanationEvidence: true,
    readOnlyRiskExplanationEvidence: true,
    fixtureDerivedRiskExplanationEvidence: true,
    riskEvidenceNodes: true,
    riskEvidenceEdges: true,
    riskEvidenceGraphs: true,
    riskExplanationTemplates: true,
    riskExplanationOutputs: true,
    riskExplanationViewModels: true,
    riskExplanationApiContracts: true,
    riskExplanationSelectors: true,
    riskExplanationLiveData: false,
    riskExplanationNetworkAccess: false,
    riskExplanationRealProviders: false,
    riskExplanationProviderAdapters: false,
    riskExplanationSolanaRpc: false,
    riskExplanationWebSocketAccess: false,
    riskExplanationGeyserYellowstone: false,
    riskExplanationPumpFunIntegration: false,
    riskExplanationDexIntegration: false,
    riskExplanationJitoIntegration: false,
    riskExplanationPersistence: false,
    riskExplanationFilesystemWrites: false,
    riskExplanationDownloads: false,
    riskExplanationRouteHandlers: false,
    riskExplanationHttpServer: false,
    riskExplanationRuntimeRequests: false,
    riskExplanationUiRendering: false,
    riskExplanationDomAccess: false,
    riskExplanationBackgroundJobs: false,
    riskExplanationScheduledJobs: false,
    riskExplanationWalletLogic: false,
    riskExplanationPrivateKeyHandling: false,
    riskExplanationSigning: false,
    riskExplanationTransactionSending: false,
    riskExplanationExecution: false,
    riskExplanationTradingSignals: false,
    riskExplanationRecommendations: false,
    riskExplanationInvestmentAdvice: false,
    riskExplanationPaperSimulation: false,
    riskExplanationLiveExecution: false,
    riskExplanationStrategySelection: false,
  };
}
