/**
 * apps/read-only-api/src/capabilities.ts
 *
 * Phase 22 — LocalReadOnlyApiCapabilities guard (extends Phase 21).
 *
 * All unsafe capability flags are permanently false.
 * canStartLocalhostServer is true only for explicit 127.0.0.1 binding.
 * Phase 21 adds canFilterFixtureData, canPaginateFixtureData, canSortFixtureData.
 * Phase 22 adds canServeResponseEnvelopes, canReturnErrorEnvelopes,
 *   canValidateQueryErrors, canProvideDeterministicMetadata, canProvideEndpointContracts.
 * No external bind, no live data, no execution of any kind.
 */

import type { LocalReadOnlyApiCapabilities } from './types.js';

/**
 * Returns the permanently-safe LocalReadOnlyApiCapabilities.
 *
 * Unsafe flags: all permanently false.
 * canStartLocalhostServer: true — valid only for 127.0.0.1 binding.
 * Phase 21 query/filter/pagination fields: true.
 * Phase 22 response contract fields: true.
 * All safe labels (fixtureOnly, analysisOnly, etc.): permanently true.
 */
export function getLocalReadOnlyApiCapabilities(): LocalReadOnlyApiCapabilities {
  return {
    // Unsafe — permanently false
    canUseLiveData: false,
    canUseSolanaRpc: false,
    canUseProviderApis: false,
    canAccessPrivateKeys: false,
    canCreateTradeIntents: false,
    canCreateExecutionPlans: false,
    canPaperTrade: false,
    canTrade: false,
    canExecute: false,
    canWriteToDatabase: false,
    canSendTelegramAlerts: false,
    canConstructTransactions: false,
    canSimulateTransactions: false,
    canCreateOrders: false,
    canCreatePositions: false,
    canCalculateLivePnl: false,
    canMutatePriorEvidence: false,
    canRenderUi: false,
    canUseExternalNetwork: false,
    // Allowed — localhost server only
    canStartLocalhostServer: true,
    canServeReadOnlyContracts: true,
    canServeFixtureReadModels: true,
    // Phase 21 — query/filter/pagination (fixture-only, in-memory only)
    canFilterFixtureData: true,
    canPaginateFixtureData: true,
    canSortFixtureData: true,
    // Phase 22 — response contract capabilities
    canServeResponseEnvelopes: true,
    canReturnErrorEnvelopes: true,
    canValidateQueryErrors: true,
    canProvideDeterministicMetadata: true,
    canProvideEndpointContracts: true,
    // Phase 23 — local consumer SDK capabilities
    consumerSdk: true,
    contractFixtures: true,
    typedRequestBuilders: true,
    responseParsers: true,
    fixtureValidation: true,
    inProcessOnlyClient: true,
    externalNetworkClient: false,
    // Phase 24 — local dashboard data adapter / view-model layer
    dashboardDataAdapter: true,
    dashboardViewModels: true,
    fixtureBackedViewModels: true,
    uiReadyDataShapes: true,
    pureViewModelTransforms: true,
    dashboardUi: false,
    externalDashboardData: false,
    // Phase 25 — local read-only dashboard UI shell
    dashboardUiShell: true,
    localReadOnlyDashboard: true,
    fixtureBackedDashboardUi: true,
    dashboardUsesViewModels: true,
    dashboardInteractionState: true,
    localDashboardFilters: true,
    inMemoryDashboardState: true,
    deterministicDashboardState: true,
    dashboardPanelVisibility: true,
    dashboardFilterSelectors: true,
    dashboardPersistentState: false,
    dashboardExternalStateSync: false,
    dashboardLiveFilters: false,
    dashboardExternalNetwork: false,
    dashboardLiveData: false,
    dashboardTradingControls: false,
    dashboardWalletControls: false,
    dashboardMutationControls: false,
    dashboardExecutionControls: false,
    dashboardWalletConnection: false,
    dashboardRealTimeUpdates: false,
    // Phase 28 — local dashboard report export models
    dashboardReportModels: true,
    dashboardReportFixtures: true,
    deterministicReportModels: true,
    reportSafetyValidation: true,
    fixtureBackedReports: true,
    dashboardReportFileExport: false,
    dashboardReportPersistence: false,
    dashboardReportExternalNetwork: false,
    dashboardReportLiveData: false,
    dashboardReportMutationControls: false,
    // Phase 29 — dashboard report serialization previews
    dashboardReportSerializationPreview: true,
    dashboardReportJsonPreview: true,
    dashboardReportMarkdownPreview: true,
    dashboardReportTextPreview: true,
    dashboardReportMetadataPreview: true,
    dashboardReportActualFileExport: false,
    dashboardReportDownloadSupport: false,
    // Phase 30 — creator intelligence fixture capabilities
    creatorIntelligenceFixtures: true,
    syntheticCreatorProfiles: true,
    creatorNarrativeFixtures: true,
    creatorRiskIndicators: true,
    creatorCredibilityIndicators: true,
    creatorFixtureSafetyValidation: true,
    creatorLiveData: false,
    creatorSocialApiAccess: false,
    creatorScraping: false,
    creatorIdentityResolution: false,
    creatorInvestmentAdvice: false,
    creatorTradingSignals: false,
    creatorExternalNetwork: false,
    creatorPersistence: false,
    // Phase 31 wallet cluster fixture capabilities
    walletClusterIntelligenceFixtures: true,
    syntheticWalletClusters: true,
    walletClusterSignalFixtures: true,
    walletClusterRiskIndicators: true,
    walletClusterQualityIndicators: true,
    walletClusterFixtureSafetyValidation: true,
    walletClusterLiveData: false,
    walletClusterChainAccess: false,
    walletClusterRpcAccess: false,
    walletClusterIdentityResolution: false,
    walletClusterInvestmentAdvice: false,
    walletClusterTradingSignals: false,
    walletClusterExternalNetwork: false,
    walletClusterPersistence: false,
    // Phase 32 manipulation evidence fixture capabilities
    manipulationEvidenceFixtures: true,
    syntheticBundleEvidence: true,
    syntheticLaunchStructureEvidence: true,
    syntheticLiquidityPatternEvidence: true,
    syntheticCoordinationEvidence: true,
    manipulationRiskIndicators: true,
    manipulationQualityIndicators: true,
    manipulationEvidenceSafetyValidation: true,
    manipulationLiveData: false,
    manipulationSolanaRpc: false,
    manipulationProviderApis: false,
    manipulationJitoIntegration: false,
    manipulationMempoolAccess: false,
    manipulationTradingSignals: false,
    manipulationInvestmentAdvice: false,
    manipulationExternalNetwork: false,
    manipulationPersistence: false,
    manipulationExecution: false,
    // Phase 33 composite evidence fixture capabilities
    compositeEvidenceFixtures: true,
    syntheticCompositeEvidence: true,
    compositeCreatorEvidenceRefs: true,
    compositeWalletClusterEvidenceRefs: true,
    compositeManipulationEvidenceRefs: true,
    compositeRiskIndicators: true,
    compositeQualityIndicators: true,
    compositeConfidenceIndicators: true,
    compositeEvidenceWeighting: true,
    compositeEvidenceSafetyValidation: true,
    compositeLiveData: false,
    compositeExternalNetwork: false,
    compositeTradingSignals: false,
    compositeInvestmentAdvice: false,
    compositeExecution: false,
    compositePersistence: false,
    // Phase 34 offline intelligence report integration capabilities
    offlineIntelligenceReportModels: true,
    offlineIntelligenceReportFixtures: true,
    offlineIntelligenceCompositeReportIntegration: true,
    offlineIntelligenceReportRiskSections: true,
    offlineIntelligenceReportQualitySections: true,
    offlineIntelligenceReportConfidenceSections: true,
    offlineIntelligenceReportSourceReferences: true,
    offlineIntelligenceReportSafetyValidation: true,
    offlineIntelligenceReportLiveData: false,
    offlineIntelligenceReportSolanaRpc: false,
    offlineIntelligenceReportProviderApis: false,
    offlineIntelligenceReportJitoIntegration: false,
    offlineIntelligenceReportMempoolAccess: false,
    offlineIntelligenceReportTradingSignals: false,
    offlineIntelligenceReportInvestmentAdvice: false,
    offlineIntelligenceReportExternalNetwork: false,
    offlineIntelligenceReportPersistence: false,
    offlineIntelligenceReportExecution: false,
    offlineIntelligenceReportFileExport: false,
    offlineIntelligenceReportDownloadSupport: false,
    // Phase 36 replay outcome fixture capabilities
    replayOutcomeFixtures: true,
    syntheticReplayOutcomes: true,
    replayOutcomeBuilders: true,
    replayOutcomeSafetyValidation: true,
    replayOutcomeCompositeEvidenceReferences: true,
    replayOutcomeReportReferences: true,
    replayOutcomeDashboardReferences: true,
    replayOutcomeLiveData: false,
    replayOutcomeRealBacktesting: false,
    replayOutcomePaperTrading: false,
    replayOutcomeLiveTrading: false,
    replayOutcomeExecution: false,
    replayOutcomeSolanaRpc: false,
    replayOutcomeExternalNetwork: false,
    replayOutcomePersistence: false,
    replayOutcomeFileExport: false,
    replayOutcomeInvestmentAdvice: false,
    replayOutcomeTradingSignals: false,
    // Phase 38 strategy candidate evaluation fixture capabilities
    strategyCandidateEvaluationFixtures: true,
    syntheticStrategyCandidates: true,
    strategyCandidateBuilders: true,
    strategyCandidateSafetyValidation: true,
    strategyCandidateScoreBandReferences: true,
    strategyCandidateRealScoring: false,
    strategyCandidateRealRanking: false,
    strategyCandidateRealBacktesting: false,
    strategyCandidatePaperTrading: false,
    strategyCandidateLiveTrading: false,
    strategyCandidateExecution: false,
    strategyCandidateSolanaRpc: false,
    strategyCandidateExternalNetwork: false,
    strategyCandidatePersistence: false,
    strategyCandidateFileExport: false,
    strategyCandidateInvestmentAdvice: false,
    strategyCandidateTradingSignals: false,
    strategyCandidateRecommendations: false,
    // Phase 39 strategy comparison matrix fixture capabilities
    strategyComparisonMatrixFixtures: true,
    syntheticStrategyComparisonMatrices: true,
    strategyComparisonMatrixBuilders: true,
    strategyComparisonMatrixSafetyValidation: true,
    strategyComparisonCandidateReferences: true,
    strategyComparisonRealScoring: false,
    strategyComparisonRealRanking: false,
    strategyComparisonRealBacktesting: false,
    strategyComparisonPaperTrading: false,
    strategyComparisonLiveTrading: false,
    strategyComparisonExecution: false,
    strategyComparisonSolanaRpc: false,
    strategyComparisonExternalNetwork: false,
    strategyComparisonPersistence: false,
    strategyComparisonFileExport: false,
    strategyComparisonInvestmentAdvice: false,
    strategyComparisonTradingSignals: false,
    strategyComparisonRecommendations: false,
    // Phase 40 strategy review dashboard fixture capabilities
    strategyReviewDashboardFixtures: true,
    syntheticStrategyReviewDashboards: true,
    strategyReviewDashboardBuilders: true,
    strategyReviewDashboardSafetyValidation: true,
    strategyReviewMatrixReferences: true,
    strategyReviewRealUiRendering: false,
    strategyReviewRealScoring: false,
    strategyReviewRealRanking: false,
    strategyReviewRecommendations: false,
    strategyReviewTradingSignals: false,
    strategyReviewPaperTrading: false,
    strategyReviewLiveTrading: false,
    strategyReviewExecution: false,
    strategyReviewSolanaRpc: false,
    strategyReviewExternalNetwork: false,
    strategyReviewPersistence: false,
    strategyReviewFileExport: false,
    strategyReviewInvestmentAdvice: false,
    // Phase 41 strategy review report fixture capabilities
    strategyReviewReportFixtures: true,
    syntheticStrategyReviewReports: true,
    strategyReviewReportBuilders: true,
    strategyReviewReportSafetyValidation: true,
    strategyReviewDashboardReferences: true,
    strategyReviewReportActualFileExport: false,
    strategyReviewReportDownloadSupport: false,
    strategyReviewReportRealUiRendering: false,
    strategyReviewReportRealScoring: false,
    strategyReviewReportRealRanking: false,
    strategyReviewReportRecommendations: false,
    strategyReviewReportTradingSignals: false,
    strategyReviewReportPaperTrading: false,
    strategyReviewReportLiveTrading: false,
    strategyReviewReportExecution: false,
    strategyReviewReportSolanaRpc: false,
    strategyReviewReportExternalNetwork: false,
    strategyReviewReportPersistence: false,
    strategyReviewReportInvestmentAdvice: false,
    // Phase 42 strategy review serialization preview fixture capabilities
    strategyReviewSerializationPreviewFixtures: true,
    syntheticStrategyReviewSerializationPreviews: true,
    strategyReviewSerializationPreviewBuilders: true,
    strategyReviewSerializationSafetyValidation: true,
    strategyReviewReportReferences: true,
    strategyReviewJsonPreview: true,
    strategyReviewMarkdownPreview: true,
    strategyReviewTextPreview: true,
    strategyReviewMetadataPreview: true,
    strategyReviewActualFileExport: false,
    strategyReviewDownloadSupport: false,
    strategyReviewSerializationExternalNetwork: false,
    strategyReviewSerializationPersistence: false,
    strategyReviewSerializationExecution: false,
    strategyReviewSerializationTradingSignals: false,
    strategyReviewSerializationInvestmentAdvice: false,
    // Phase 43 strategy review export planning fixture capabilities
    strategyReviewExportPlanningFixtures: true,
    syntheticStrategyReviewExportPlans: true,
    strategyReviewExportPlanBuilders: true,
    strategyReviewExportPlanSafetyValidation: true,
    strategyReviewSerializationPreviewReferences: true,
    strategyReviewFilesystemWrites: false,
    strategyReviewPdfGeneration: false,
    strategyReviewCsvGeneration: false,
    strategyReviewHtmlGeneration: false,
    strategyReviewExportExternalNetwork: false,
    strategyReviewExportPersistence: false,
    strategyReviewExportExecution: false,
    strategyReviewExportTradingSignals: false,
    strategyReviewExportInvestmentAdvice: false,
    // Phase 44 strategy review export queue fixture capabilities
    strategyReviewExportQueueFixtures: true,
    syntheticStrategyReviewExportQueues: true,
    strategyReviewExportQueueBuilders: true,
    strategyReviewExportQueueSafetyValidation: true,
    strategyReviewExportPlanReferences: true,
    strategyReviewActualQueueWorkers: false,
    strategyReviewScheduledJobs: false,
    strategyReviewBackgroundJobs: false,
    strategyReviewExportQueueExternalNetwork: false,
    strategyReviewExportQueuePersistence: false,
    strategyReviewExportQueueExecution: false,
    strategyReviewExportQueueTradingSignals: false,
    strategyReviewExportQueueInvestmentAdvice: false,
    // Phase 45 strategy review export audit fixture capabilities
    strategyReviewExportAuditFixtures: true,
    syntheticStrategyReviewExportAudits: true,
    strategyReviewExportAuditBuilders: true,
    strategyReviewExportAuditSafetyValidation: true,
    strategyReviewExportQueueReferences: true,
    strategyReviewActualAuditLogs: false,
    strategyReviewAuditPersistence: false,
    strategyReviewAuditFileWrites: false,
    strategyReviewAuditExternalNetwork: false,
    strategyReviewAuditQueueWorkers: false,
    strategyReviewAuditScheduledJobs: false,
    strategyReviewAuditBackgroundJobs: false,
    strategyReviewAuditActualFileExport: false,
    strategyReviewAuditDownloadSupport: false,
    strategyReviewAuditExecution: false,
    strategyReviewAuditTradingSignals: false,
    strategyReviewAuditInvestmentAdvice: false,
    // Phase 46 strategy review export audit report fixture capabilities
    strategyReviewExportAuditReportFixtures: true,
    syntheticStrategyReviewExportAuditReports: true,
    deterministicStrategyReviewExportAuditReports: true,
    localOnlyStrategyReviewExportAuditReports: true,
    readOnlyStrategyReviewExportAuditReports: true,
    strategyReviewActualAuditReports: false,
    strategyReviewReportDownloads: false,
    strategyReviewReportPdfGeneration: false,
    strategyReviewReportCsvGeneration: false,
    strategyReviewReportHtmlGeneration: false,
    strategyReviewReportFilesystemWrites: false,
    strategyReviewReportBackgroundJobs: false,
    strategyReviewReportScheduledJobs: false,
    strategyReviewReportLiveData: false,
    strategyReviewReportNetworkAccess: false,
    // Phase 47 strategy review export audit report view-model capabilities
    strategyReviewExportAuditReportViewModels: true,
    syntheticStrategyReviewExportAuditReportViewModels: true,
    deterministicStrategyReviewExportAuditReportViewModels: true,
    localOnlyStrategyReviewExportAuditReportViewModels: true,
    readOnlyStrategyReviewExportAuditReportViewModels: true,
    fixtureDerivedStrategyReviewExportAuditReportViewModels: true,
    strategyReviewExportAuditReportViewModelLiveData: false,
    strategyReviewExportAuditReportViewModelNetworkAccess: false,
    strategyReviewExportAuditReportViewModelPersistence: false,
    strategyReviewExportAuditReportViewModelFilesystemWrites: false,
    strategyReviewExportAuditReportViewModelDownloads: false,
    strategyReviewExportAuditReportViewModelPdfGeneration: false,
    strategyReviewExportAuditReportViewModelCsvGeneration: false,
    strategyReviewExportAuditReportViewModelHtmlGeneration: false,
    strategyReviewExportAuditReportViewModelUiRendering: false,
    strategyReviewExportAuditReportViewModelDomAccess: false,
    strategyReviewExportAuditReportViewModelBackgroundJobs: false,
    strategyReviewExportAuditReportViewModelScheduledJobs: false,
    strategyReviewExportAuditReportViewModelExecution: false,
    strategyReviewExportAuditReportViewModelTradingSignals: false,
    strategyReviewExportAuditReportViewModelRecommendations: false,
    strategyReviewExportAuditReportViewModelInvestmentAdvice: false,
    // Phase 48 strategy review export audit report read-only API contract capabilities
    strategyReviewExportAuditReportApiContracts: true,
    syntheticStrategyReviewExportAuditReportApiContracts: true,
    deterministicStrategyReviewExportAuditReportApiContracts: true,
    localOnlyStrategyReviewExportAuditReportApiContracts: true,
    readOnlyStrategyReviewExportAuditReportApiContracts: true,
    fixtureDerivedStrategyReviewExportAuditReportApiContracts: true,
    strategyReviewExportAuditReportApiContractLiveData: false,
    strategyReviewExportAuditReportApiContractNetworkAccess: false,
    strategyReviewExportAuditReportApiContractPersistence: false,
    strategyReviewExportAuditReportApiContractFilesystemWrites: false,
    strategyReviewExportAuditReportApiContractDownloads: false,
    strategyReviewExportAuditReportApiContractPdfGeneration: false,
    strategyReviewExportAuditReportApiContractCsvGeneration: false,
    strategyReviewExportAuditReportApiContractHtmlGeneration: false,
    strategyReviewExportAuditReportApiContractRouteHandlers: false,
    strategyReviewExportAuditReportApiContractHttpServer: false,
    strategyReviewExportAuditReportApiContractRuntimeRequests: false,
    strategyReviewExportAuditReportApiContractUiRendering: false,
    strategyReviewExportAuditReportApiContractDomAccess: false,
    strategyReviewExportAuditReportApiContractBackgroundJobs: false,
    strategyReviewExportAuditReportApiContractScheduledJobs: false,
    strategyReviewExportAuditReportApiContractExecution: false,
    strategyReviewExportAuditReportApiContractTradingSignals: false,
    strategyReviewExportAuditReportApiContractRecommendations: false,
    strategyReviewExportAuditReportApiContractInvestmentAdvice: false,
    // Phase 49 strategy review export audit report API contract selector capabilities
    strategyReviewExportAuditReportApiContractSelectors: true,
    syntheticStrategyReviewExportAuditReportApiContractSelectors: true,
    deterministicStrategyReviewExportAuditReportApiContractSelectors: true,
    localOnlyStrategyReviewExportAuditReportApiContractSelectors: true,
    readOnlyStrategyReviewExportAuditReportApiContractSelectors: true,
    fixtureDerivedStrategyReviewExportAuditReportApiContractSelectors: true,
    pureStrategyReviewExportAuditReportApiContractSelectors: true,
    strategyReviewExportAuditReportApiContractSelectorLiveData: false,
    strategyReviewExportAuditReportApiContractSelectorNetworkAccess: false,
    strategyReviewExportAuditReportApiContractSelectorPersistence: false,
    strategyReviewExportAuditReportApiContractSelectorFilesystemWrites: false,
    strategyReviewExportAuditReportApiContractSelectorDownloads: false,
    strategyReviewExportAuditReportApiContractSelectorPdfGeneration: false,
    strategyReviewExportAuditReportApiContractSelectorCsvGeneration: false,
    strategyReviewExportAuditReportApiContractSelectorHtmlGeneration: false,
    strategyReviewExportAuditReportApiContractSelectorRouteHandlers: false,
    strategyReviewExportAuditReportApiContractSelectorHttpServer: false,
    strategyReviewExportAuditReportApiContractSelectorRuntimeRequests: false,
    strategyReviewExportAuditReportApiContractSelectorUiRendering: false,
    strategyReviewExportAuditReportApiContractSelectorDomAccess: false,
    strategyReviewExportAuditReportApiContractSelectorBackgroundJobs: false,
    strategyReviewExportAuditReportApiContractSelectorScheduledJobs: false,
    strategyReviewExportAuditReportApiContractSelectorExecution: false,
    strategyReviewExportAuditReportApiContractSelectorTradingSignals: false,
    strategyReviewExportAuditReportApiContractSelectorRecommendations: false,
    strategyReviewExportAuditReportApiContractSelectorInvestmentAdvice: false,
    // Phase 50 strategy review export audit report selector view-model capabilities
    strategyReviewExportAuditReportSelectorViewModels: true,
    syntheticStrategyReviewExportAuditReportSelectorViewModels: true,
    deterministicStrategyReviewExportAuditReportSelectorViewModels: true,
    localOnlyStrategyReviewExportAuditReportSelectorViewModels: true,
    readOnlyStrategyReviewExportAuditReportSelectorViewModels: true,
    fixtureDerivedStrategyReviewExportAuditReportSelectorViewModels: true,
    strategyReviewExportAuditReportSelectorViewModelLiveData: false,
    strategyReviewExportAuditReportSelectorViewModelNetworkAccess: false,
    strategyReviewExportAuditReportSelectorViewModelPersistence: false,
    strategyReviewExportAuditReportSelectorViewModelFilesystemWrites: false,
    strategyReviewExportAuditReportSelectorViewModelDownloads: false,
    strategyReviewExportAuditReportSelectorViewModelPdfGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelCsvGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelHtmlGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelRouteHandlers: false,
    strategyReviewExportAuditReportSelectorViewModelHttpServer: false,
    strategyReviewExportAuditReportSelectorViewModelRuntimeRequests: false,
    strategyReviewExportAuditReportSelectorViewModelUiRendering: false,
    strategyReviewExportAuditReportSelectorViewModelDomAccess: false,
    strategyReviewExportAuditReportSelectorViewModelBackgroundJobs: false,
    strategyReviewExportAuditReportSelectorViewModelScheduledJobs: false,
    strategyReviewExportAuditReportSelectorViewModelExecution: false,
    strategyReviewExportAuditReportSelectorViewModelTradingSignals: false,
    strategyReviewExportAuditReportSelectorViewModelRecommendations: false,
    strategyReviewExportAuditReportSelectorViewModelInvestmentAdvice: false,
    // Phase 51 strategy review export audit report selector view-model API contract capabilities
    strategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    syntheticStrategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    deterministicStrategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    localOnlyStrategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    readOnlyStrategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    fixtureDerivedStrategyReviewExportAuditReportSelectorViewModelApiContracts: true,
    strategyReviewExportAuditReportSelectorViewModelApiContractLiveData: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractNetworkAccess: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractPersistence: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractFilesystemWrites: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractDownloads: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractPdfGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractCsvGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractHtmlGeneration: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractRouteHandlers: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractHttpServer: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractRuntimeRequests: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractUiRendering: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractDomAccess: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractBackgroundJobs: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractScheduledJobs: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractExecution: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractTradingSignals: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractRecommendations: false,
    strategyReviewExportAuditReportSelectorViewModelApiContractInvestmentAdvice: false,
    // Safety labels
    fixtureOnly: true,
    analysisOnly: true,
    nonExecutable: true,
    readOnly: true,
    localOnly: true,
  };
}
