import type { HistoricalSnapshotScenarioGeneratorCapabilities } from './types.js';

export function getHistoricalSnapshotScenarioGeneratorCapabilities(): HistoricalSnapshotScenarioGeneratorCapabilities {
  return {
    historicalSnapshotScenarioGenerator: true,
    deterministicSnapshotScenarioGeneration: true,
    fixtureDerivedScenarioGeneration: true,
    snapshotSourceSelectionModels: true,
    snapshotGeneratedScenarioDescriptors: true,
    snapshotReplayDescriptors: true,
    snapshotScenarioLineageModels: true,
    snapshotScenarioIntegrityContracts: true,
    snapshotScenarioValidationContracts: true,
    snapshotScenarioRejectionContracts: true,
    snapshotScenarioQualityLinkage: true,
    snapshotScenarioReliabilityLinkage: true,
    snapshotScenarioAuditReports: true,
    snapshotScenarioViewModels: true,
    snapshotScenarioApiContracts: true,
    snapshotScenarioSelectors: true,
    snapshotScenarioLiveGeneration: false,
    snapshotScenarioRuntimeGeneration: false,
    snapshotScenarioLiveIngestion: false,
    snapshotScenarioRuntimeIngestion: false,
    snapshotScenarioLiveReplayImport: false,
    snapshotScenarioLiveNetworkAccess: false,
    snapshotScenarioRuntimeCollectors: false,
    snapshotScenarioSecretsRequired: false,
    snapshotScenarioApiKeyRequired: false,
    snapshotScenarioWriteMethods: false,
    snapshotScenarioWalletLogic: false,
    snapshotScenarioPrivateKeyHandling: false,
    snapshotScenarioSigning: false,
    snapshotScenarioTransactionSending: false,
    snapshotScenarioExecution: false,
    snapshotScenarioTradingSignals: false,
    snapshotScenarioRecommendations: false,
    snapshotScenarioInvestmentAdvice: false,
    snapshotScenarioRouteHandlers: false,
    snapshotScenarioRuntimeRequests: false,
    snapshotScenarioUiRendering: false,
    snapshotScenarioDomAccess: false,
    snapshotScenarioPersistence: false,
    snapshotScenarioFilesystemWrites: false,
    snapshotScenarioBackgroundJobs: false,
    snapshotScenarioScheduledJobs: false,
    snapshotScenarioRealOrders: false,
    snapshotScenarioRealFunds: false,
    snapshotScenarioRealPnL: false,
    snapshotScenarioProviderExpansion: false,
  };
}
