import type { MultiProviderReadOnlyFoundationCapabilities } from './types.js';

export function getMultiProviderReadOnlyFoundationCapabilities(): MultiProviderReadOnlyFoundationCapabilities {
  return {
    multiProviderReadOnlyFoundation: true,
    multiProviderReadOnlyRegistry: true,
    deterministicMultiProviderRegistry: true,
    localOnlyMultiProviderRegistry: true,
    fixtureDerivedMultiProviderRegistry: true,
    multiProviderNormalization: true,
    providerHealthScoring: true,
    staleDataDetection: true,
    readOnlyFreshnessPolicies: true,
    readOnlyCachePolicyContracts: true,
    providerSelectionFixtures: true,
    providerFallbackFixtures: true,
    multiProviderConformanceReports: true,
    multiProviderViewModels: true,
    multiProviderApiContracts: true,
    multiProviderSelectors: true,
    multiProviderLiveDataDefault: false,
    multiProviderNetworkAccessDefault: false,
    multiProviderWriteMethods: false,
    multiProviderWalletLogic: false,
    multiProviderPrivateKeyHandling: false,
    multiProviderSigning: false,
    multiProviderTransactionSending: false,
    multiProviderExecution: false,
    multiProviderTradingSignals: false,
    multiProviderRecommendations: false,
    multiProviderInvestmentAdvice: false,
    multiProviderRouteHandlers: false,
    multiProviderRuntimeRequests: false,
    multiProviderUiRendering: false,
    multiProviderDomAccess: false,
    multiProviderPersistence: false,
    multiProviderFilesystemWrites: false,
    multiProviderBackgroundJobs: false,
    multiProviderScheduledJobs: false,
    multiProviderRealOrders: false,
    multiProviderRealFunds: false,
    multiProviderRealPnL: false,
    multiProviderLiveStrategySelection: false,
    multiProviderAutoExecution: false,
  };
}
