import type { PreLiveSafetyCertificationCapabilities } from './types.js';

export function getPreLiveSafetyCertificationCapabilities(): PreLiveSafetyCertificationCapabilities {
  return {
    preLiveSafetyCertification: true,
    deterministicPreLiveSafetyFixtures: true,
    preLiveSafetyGates: true,
    preLiveReadinessChecklists: true,
    preLiveCertificationContracts: true,
    preLiveEvidenceBundles: true,
    preLiveSignoffModels: true,
    preLiveApprovalPolicies: true,
    preLiveRejectionContracts: true,
    preLiveCapabilityAudits: true,
    preLiveSafetyInvariants: true,
    preLiveProviderReadinessLinkage: true,
    preLiveReplayReadinessLinkage: true,
    preLiveScenarioReadinessLinkage: true,
    preLiveSmokeReadinessLinkage: true,
    preLiveRiskReadinessLinkage: true,
    preLiveScorecards: true,
    preLiveCertificationReports: true,
    preLiveViewModels: true,
    preLiveApiContracts: true,
    preLiveSelectors: true,
    preLiveUnlockAuthority: false,
    preLiveLiveTrading: false,
    preLiveManualTrading: false,
    preLiveLimitedLiveUnlock: false,
    preLiveFullAutoUnlock: false,
    preLiveExecution: false,
    preLiveTransactionBuilding: false,
    preLiveTransactionSending: false,
    preLiveWalletLogic: false,
    preLivePrivateKeyHandling: false,
    preLiveSigning: false,
    preLiveTradingSignals: false,
    preLiveRecommendations: false,
    preLiveInvestmentAdvice: false,
    preLiveRealOrders: false,
    preLiveRealFunds: false,
    preLiveRealPnL: false,
    preLiveLiveNetworkDefault: false,
    preLiveScheduledJobs: false,
    preLiveRuntimeMonitoring: false,
    preLiveRuntimeCollectors: false,
    preLiveProviderExpansion: false,
    preLiveSecretsRequired: false,
    preLiveFilesystemWrites: false,
    preLivePersistence: false,
    preLiveRouteHandlers: false,
    preLiveRuntimeRequests: false,
    preLiveUiRendering: false,
    preLiveDomAccess: false,
    preLiveBackgroundJobs: false,
  };
}
