import type { CrossProviderDataQualityCapabilities } from './types.js';

export function getCrossProviderDataQualityCapabilities(): CrossProviderDataQualityCapabilities {
  return {
    crossProviderDataQuality: true,
    crossProviderComparison: true,
    deterministicProviderMismatchDetection: true,
    providerReconciliationReports: true,
    providerConfidenceScoring: true,
    providerProvenanceTracking: true,
    readOnlyProviderEnrichmentContracts: true,
    fixtureDerivedProviderQualityModels: true,
    localOnlyProviderQualityModels: true,
    crossProviderQualityViewModels: true,
    crossProviderQualityApiContracts: true,
    crossProviderQualitySelectors: true,
    crossProviderLiveData: false,
    crossProviderNetworkAccess: false,
    crossProviderWriteMethods: false,
    crossProviderWalletLogic: false,
    crossProviderPrivateKeyHandling: false,
    crossProviderSigning: false,
    crossProviderTransactionSending: false,
    crossProviderExecution: false,
    crossProviderTradingSignals: false,
    crossProviderRecommendations: false,
    crossProviderInvestmentAdvice: false,
    crossProviderRouteHandlers: false,
    crossProviderRuntimeRequests: false,
    crossProviderUiRendering: false,
    crossProviderDomAccess: false,
    crossProviderPersistence: false,
    crossProviderFilesystemWrites: false,
    crossProviderBackgroundJobs: false,
    crossProviderScheduledJobs: false,
    crossProviderRealOrders: false,
    crossProviderRealFunds: false,
    crossProviderRealPnL: false,
    crossProviderLiveReconciliation: false,
    crossProviderAutoExecution: false,
  };
}
