/**
 * apps/dashboard/src/index.ts
 *
 * Phase 29 — Local Dashboard Report Serialization Preview v1 — Public API Barrel
 *
 * Exports the local read-only dashboard UI shell components,
 * view model source, Phase 25/26/27/28/29 capability metadata, Phase 26 local
 * in-memory interaction state helpers, Phase 27 snapshots, Phase 28 reports, and
 * Phase 29 serialization previews.
 *
 * What this module provides:
 *   - DashboardShell — top-level dashboard shell component
 *   - SafetyBanner — safety boundary notice component
 *   - MetadataPanel — phase/safety metadata panel
 *   - HealthPanel — health view model panel
 *   - CapabilitiesPanel — capabilities view model panel
 *   - OverviewPanel — overview view model panel
 *   - EvidencePanel — evidence view model panel
 *   - SafetyPanel — safety view model panel
 *   - EmptyState — empty state panel
 *   - LoadingState — loading state panel
 *   - ErrorState — error state panel
 *   - UnavailableState — unavailable state panel
 *   - StatusBadge — status badge component
 *   - buildFixtureDashboardViewModel — fixture-backed view model builder
 *   - getDashboardUiShellCapabilities — Phase 25 capability flags
 *   - Phase 26 local interaction state types/helpers/selectors
 *   - Phase 28 local report model types/helpers/fixtures/validation
 *   - Phase 29 local report serialization preview types/helpers/fixtures/validation
 *   - PHASE_25_SAFETY_BOUNDARY — shared safety boundary constant
 *   - All dashboard UI shell types
 *
 * What this module does NOT provide:
 *   - No live data
 *   - No network requests (no HTTP or web socket clients)
 *   - No Solana RPC
 *   - No provider APIs
 *   - No wallet integration
 *   - No private keys
 *   - No execution logic
 *   - No trading controls
 *   - No mutation controls
 *   - No external network access
 *   - No browser-specific APIs for unsafe side effects
 *   - No filesystem or browser report export behavior
 *
 * IMPORTANT: This UI shell is local-only, read-only, fixture-only,
 * deterministic, offline, non-mutating, and external-network-free.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type {
  DashboardItem,
  DashboardSection,
  StatusBadgeResult,
  DashboardSafetyBoundary,
  DashboardRenderResult,
  SafetyBannerResult,
  DashboardNavEntry,
  DashboardShellResult,
  DashboardUiShellCapabilities,
} from './types.js';

// ─── Components ───────────────────────────────────────────────────────────────

export { StatusBadge } from './components/StatusBadge.js';
export type { StatusBadgeProps } from './components/StatusBadge.js';

export { SafetyBanner, PHASE_25_SAFETY_BOUNDARY, SAFETY_BANNER_NOTICES } from './components/SafetyBanner.js';

export { MetadataPanel } from './components/MetadataPanel.js';
export type { MetadataPanelProps } from './components/MetadataPanel.js';

export { HealthPanel } from './components/HealthPanel.js';
export type { HealthPanelProps } from './components/HealthPanel.js';

export { CapabilitiesPanel } from './components/CapabilitiesPanel.js';
export type { CapabilitiesPanelProps } from './components/CapabilitiesPanel.js';

export { OverviewPanel } from './components/OverviewPanel.js';
export type { OverviewPanelProps } from './components/OverviewPanel.js';

export { EvidencePanel } from './components/EvidencePanel.js';
export type { EvidencePanelProps } from './components/EvidencePanel.js';

export { SafetyPanel } from './components/SafetyPanel.js';
export type { SafetyPanelProps } from './components/SafetyPanel.js';

export { EmptyState } from './components/EmptyState.js';
export type { EmptyStateProps } from './components/EmptyState.js';

export { LoadingState } from './components/LoadingState.js';
export type { LoadingStateProps } from './components/LoadingState.js';

export { ErrorState } from './components/ErrorState.js';
export type { ErrorStateProps } from './components/ErrorState.js';

export { UnavailableState } from './components/UnavailableState.js';
export type { UnavailableStateProps } from './components/UnavailableState.js';

export { DashboardShell } from './components/DashboardShell.js';
export type { DashboardShellProps } from './components/DashboardShell.js';

// ─── View model source ────────────────────────────────────────────────────────

export {
  buildFixtureDashboardViewModel,
  getViewModelSourceDescription,
  getViewModelSourceMeta,
} from './view-model-source.js';

// ─── Capabilities ─────────────────────────────────────────────────────────────

export { getDashboardUiShellCapabilities } from './capabilities.js';

// ─── Phase 26 interaction state ────────────────────────────────────────────────

export type {
  DashboardInteractionState,
  DashboardPanelId,
  DashboardPanelVisibilityState,
  DashboardFilterState,
  DashboardEvidenceFilterState,
  DashboardSafetyFilterState,
  DashboardSortState,
  DashboardStateAction,
  DashboardStateActionType,
  DashboardStateUpdateResult,
  DashboardStateValidationResult,
  DashboardStateSelectorResult,
  DashboardStateResetMode,
  DashboardEvidenceItem,
  DashboardSafetyItem,
} from './state/index.js';

export {
  DASHBOARD_PANEL_IDS,
  DASHBOARD_EVIDENCE_SEVERITIES,
  DASHBOARD_ITEM_STATUS_FILTERS,
  DASHBOARD_LOCAL_ITEM_STATES,
  DASHBOARD_EVIDENCE_SORT_FIELDS,
  DASHBOARD_SAFETY_SORT_FIELDS,
  DASHBOARD_SORT_DIRECTIONS,
  createDefaultDashboardInteractionState,
  createDefaultDashboardPanelVisibilityState,
  createDefaultDashboardEvidenceFilterState,
  createDefaultDashboardSafetyFilterState,
  createDefaultDashboardFilterState,
  createDefaultDashboardSortState,
  sanitizeDashboardFilterInput,
  sanitizeDashboardPanelId,
  sanitizeDashboardEvidenceFilters,
  sanitizeDashboardSafetyFilters,
  sanitizeDashboardEvidenceSortField,
  sanitizeDashboardSafetySortField,
  sanitizeDashboardSortDirection,
  sanitizeDashboardStatusFilter,
  sanitizeDashboardLocalStatusFilter,
  validateDashboardInteractionState,
  buildDashboardEvidenceItems,
  buildDashboardSafetyItems,
  applyDashboardEvidenceFilters,
  applyDashboardSafetyFilters,
  applyDashboardEvidenceSort,
  applyDashboardSafetySort,
  setDashboardActivePanel,
  toggleDashboardPanelVisibility,
  setDashboardPanelVisibility,
  updateDashboardEvidenceFilters,
  updateDashboardSafetyFilters,
  updateDashboardSortState,
  resetDashboardInteractionState,
  updateDashboardInteractionState,
  validateAndNormalizeDashboardInteractionState,
  selectDashboardPanels,
  selectVisibleDashboardPanels,
  selectActiveDashboardPanel,
  selectFilteredEvidenceItems,
  selectFilteredSafetyItems,
  selectDashboardRenderModel,
  applyDashboardInteractionState,
} from './state/index.js';

// ─── Phase 27 render snapshots ─────────────────────────────────────────────────

export type {
  DashboardRenderSnapshot,
  DashboardRenderSnapshotName,
  DashboardRenderSnapshotKind,
  DashboardRenderSnapshotFixture,
  DashboardRenderSnapshotSuite,
  DashboardRenderSnapshotMeta,
  DashboardRenderSnapshotValidationResult,
  DashboardRenderSnapshotValidationIssue,
  DashboardRenderSnapshotBuildInput,
  DashboardRenderSnapshotBuildResult,
  DashboardRenderSnapshotSafetyResult,
  DashboardRenderSnapshotRegressionCase,
  DashboardSnapshotCapabilities,
} from './snapshots/index.js';

export {
  DASHBOARD_RENDER_SNAPSHOT_NAMES,
  DASHBOARD_RENDER_SNAPSHOT_KINDS,
  buildDashboardRenderSnapshot,
  buildDefaultDashboardRenderSnapshot,
  buildFilteredDashboardRenderSnapshot,
  buildPanelRenderSnapshot,
  buildStateRenderSnapshot,
  buildSafetyBannerSnapshot,
  buildEmptyStateSnapshot,
  buildLoadingStateSnapshot,
  buildErrorStateSnapshot,
  buildUnavailableStateSnapshot,
  buildSafetyBoundarySnapshot,
  buildMalformedInputSafeSnapshot,
  isDashboardRenderSnapshotName,
  isDashboardRenderSnapshotKind,
  isDashboardShellResult,
  isSafetyBannerResult,
  normalizeDashboardRenderSnapshot,
  serializeDashboardRenderSnapshot,
  isDashboardRenderSnapshotSerializable,
  areDashboardRenderSnapshotsEqual,
  getDashboardRenderSnapshotSummary,
  validateDashboardRenderSnapshot,
  validateDashboardRenderSnapshotSafety,
  DEFAULT_DASHBOARD_SHELL_FIXTURE,
  SAFETY_BANNER_FIXTURE,
  METADATA_PANEL_FIXTURE,
  HEALTH_PANEL_FIXTURE,
  CAPABILITIES_PANEL_FIXTURE,
  OVERVIEW_PANEL_FIXTURE,
  EVIDENCE_PANEL_FIXTURE,
  SAFETY_PANEL_FIXTURE,
  EMPTY_STATE_FIXTURE,
  LOADING_STATE_FIXTURE,
  ERROR_STATE_FIXTURE,
  UNAVAILABLE_STATE_FIXTURE,
  ACTIVE_PANEL_FIXTURE,
  HIDDEN_PANEL_FIXTURE,
  FILTERED_EVIDENCE_FIXTURE,
  FILTERED_SAFETY_FIXTURE,
  RESET_INTERACTION_STATE_FIXTURE,
  NO_RESULTS_FILTERED_FIXTURE,
  MALFORMED_INPUT_SAFE_FIXTURE,
  SAFETY_BOUNDARY_FIXTURE,
  PHASE_27_REGRESSION_FIXTURES,
  PHASE_27_FIXTURE_SUITE,
  listDashboardRenderSnapshotFixtures,
  getDashboardRenderSnapshotFixture,
  getDashboardSnapshotCapabilities,
} from './snapshots/index.js';

// ─── Phase 28 report export models ──────────────────────────────────────────────

export type {
  DashboardReportModel,
  DashboardReportName,
  DashboardReportKind,
  DashboardReportSection,
  DashboardReportSectionKind,
  DashboardReportMeta,
  DashboardReportSummary,
  DashboardReportSafetyBoundary,
  DashboardReportValidationResult,
  DashboardReportValidationIssue,
  DashboardReportBuildInput,
  DashboardReportBuildResult,
  DashboardReportSafetyResult,
  DashboardReportFixture,
  DashboardReportFixtureName,
  DashboardReportCapabilities,
} from './reports/index.js';

export {
  DASHBOARD_REPORT_NAMES,
  DASHBOARD_REPORT_KINDS,
  DASHBOARD_REPORT_SECTION_KINDS,
  buildDashboardReportModel,
  buildDefaultDashboardReportModel,
  buildSnapshotInventoryReportModel,
  buildDashboardReportSection,
  buildDashboardSafetyBoundaryReport,
  buildSnapshotBackedReportFromFixture,
  normalizeDashboardReportModel,
  serializeDashboardReportModel,
  isDashboardReportSerializable,
  areDashboardReportsEqual,
  validateDashboardReportModel,
  validateDashboardReportSafety,
  FULL_DASHBOARD_REPORT_FIXTURE,
  HEALTH_REPORT_SECTION_FIXTURE,
  CAPABILITIES_REPORT_SECTION_FIXTURE,
  OVERVIEW_REPORT_SECTION_FIXTURE,
  EVIDENCE_REPORT_SECTION_FIXTURE,
  SAFETY_REPORT_SECTION_FIXTURE,
  METADATA_REPORT_SECTION_FIXTURE,
  INTERACTION_STATE_REPORT_SECTION_FIXTURE,
  FILTERED_EVIDENCE_REPORT_SECTION_FIXTURE,
  FILTERED_SAFETY_REPORT_SECTION_FIXTURE,
  SNAPSHOT_INVENTORY_REPORT_FIXTURE,
  SAFETY_BOUNDARY_REPORT_FIXTURE,
  ERROR_STATE_REPORT_FIXTURE,
  EMPTY_STATE_REPORT_FIXTURE,
  LOADING_STATE_REPORT_FIXTURE,
  UNAVAILABLE_STATE_REPORT_FIXTURE,
  NO_RESULTS_REPORT_FIXTURE,
  MALFORMED_INPUT_SAFE_REPORT_FIXTURE,
  REPORT_VALIDATION_FAILURE_EXAMPLE_FIXTURE,
  EXPORT_DISABLED_SAFETY_REPORT_FIXTURE,
  PHASE_28_REPORT_FIXTURES,
  listDashboardReportFixtures,
  getDashboardReportFixture,
  getDashboardReportCapabilities,
} from './reports/index.js';

// ─── Phase 29 report serialization previews ─────────────────────────────────────

export type {
  DashboardReportSerializationPreview,
  DashboardReportSerializationPreviewFormat,
  DashboardReportSerializationPreviewName,
  DashboardReportSerializationPreviewKind,
  DashboardReportSerializationPreviewMeta,
  DashboardReportSerializationPreviewSafetyBoundary,
  DashboardReportSerializationPreviewBuildInput,
  DashboardReportSerializationPreviewBuildResult,
  DashboardReportSerializationPreviewValidationResult,
  DashboardReportSerializationPreviewValidationIssue,
  DashboardReportSerializationPreviewSafetyResult,
  DashboardReportSerializationPreviewFixture,
  DashboardReportSerializationPreviewFixtureName,
  DashboardReportSerializationPreviewCapabilities,
} from './report-serialization/index.js';

export {
  DASHBOARD_REPORT_SERIALIZATION_PREVIEW_FORMATS,
  DASHBOARD_REPORT_SERIALIZATION_PREVIEW_NAMES,
  DASHBOARD_REPORT_SERIALIZATION_PREVIEW_KINDS,
  buildDashboardReportSerializationPreview,
  buildJsonReportPreview,
  buildMarkdownReportPreview,
  buildTextReportPreview,
  buildMetadataReportPreview,
  sortKeysDeep,
  stablePrettyJsonStringify,
  stableDeterministicChecksum,
  normalizeDashboardReportSerializationPreview,
  serializeDashboardReportSerializationPreview,
  isDashboardReportSerializationPreviewSerializable,
  areDashboardReportSerializationPreviewsEqual,
  validateDashboardReportSerializationPreview,
  validateDashboardReportSerializationPreviewSafety,
  FULL_DASHBOARD_JSON_PREVIEW_FIXTURE,
  FULL_DASHBOARD_MARKDOWN_PREVIEW_FIXTURE,
  FULL_DASHBOARD_TEXT_PREVIEW_FIXTURE,
  METADATA_ONLY_PREVIEW_FIXTURE,
  HEALTH_SECTION_PREVIEW_FIXTURE,
  CAPABILITIES_SECTION_PREVIEW_FIXTURE,
  OVERVIEW_SECTION_PREVIEW_FIXTURE,
  EVIDENCE_SECTION_PREVIEW_FIXTURE,
  SAFETY_SECTION_PREVIEW_FIXTURE,
  SNAPSHOT_INVENTORY_PREVIEW_FIXTURE,
  SAFETY_BOUNDARY_PREVIEW_FIXTURE,
  EXPORT_DISABLED_PREVIEW_FIXTURE,
  MALFORMED_INPUT_SAFE_PREVIEW_FIXTURE,
  VALIDATION_FAILURE_PREVIEW_FIXTURE,
  NO_RESULTS_PREVIEW_FIXTURE,
  PHASE_29_SERIALIZATION_PREVIEW_FIXTURES,
  listDashboardReportSerializationPreviewFixtures,
  getDashboardReportSerializationPreviewFixture,
} from './report-serialization/index.js';

// ─── Phase 35 composite evidence dashboard/report fixtures ────────────────────

export type {
  CompositeEvidenceDashboardReportFixture,
  CompositeEvidenceDashboardReportFixtureName,
  CompositeEvidenceDashboardReportFixtureKind,
  CompositeEvidenceDashboardFixture,
  CompositeEvidenceReportFixture,
  CompositeEvidencePanelFixture,
  CompositeEvidenceReportSectionFixture,
  CompositeEvidenceFixtureMeta,
  CompositeEvidenceFixtureSummary,
  CompositeEvidenceFixtureValidationResult,
  CompositeEvidenceFixtureValidationIssue,
  CompositeEvidenceFixtureSafetyResult,
  CompositeEvidenceFixtureBuildInput,
  CompositeEvidenceFixtureBuildResult,
  CompositeEvidenceDashboardReportFixtureCapabilities,
} from './composite-evidence-fixtures/index.js';

export {
  PHASE_35_COMPOSITE_EVIDENCE_DASHBOARD_REPORT_FIXTURES_GENERATED_AT,
  PHASE_35_COMPOSITE_EVIDENCE_DASHBOARD_REPORT_FIXTURES_SOURCE,
  COMPOSITE_EVIDENCE_DASHBOARD_REPORT_FIXTURE_NAMES,
  COMPOSITE_EVIDENCE_DASHBOARD_REPORT_FIXTURE_KINDS,
  normalizeCompositeEvidenceDashboardReportFixture,
  normalizeCompositeEvidenceDashboardFixture,
  normalizeCompositeEvidenceReportFixture,
  isCompositeEvidenceDashboardReportFixtureSerializable,
  areCompositeEvidenceDashboardReportFixturesEqual,
  isValidCompositeEvidenceFixtureName,
  isValidCompositeEvidenceFixtureKind,
  validateCompositeEvidenceDashboardReportFixture,
  validateCompositeEvidenceDashboardReportSafety,
  buildCompositeEvidenceDashboardFixture,
  buildCompositeEvidenceReportFixture,
  buildCompositeEvidenceDashboardReportFixture,
  buildCompositeEvidenceFixture,
  CLEAN_LOW_RISK_DASHBOARD_FIXTURE,
  CREATOR_CREDIBLE_WALLET_BENIGN_DASHBOARD_FIXTURE,
  CREATOR_RISK_WALLET_RISK_DASHBOARD_FIXTURE,
  MANIPULATION_RISK_DOMINATES_DASHBOARD_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_DASHBOARD_FIXTURE,
  INSUFFICIENT_DATA_DASHBOARD_FIXTURE,
  HIGH_RISK_MULTI_EVIDENCE_DASHBOARD_FIXTURE,
  SAFETY_BOUNDARY_DASHBOARD_FIXTURE,
  MALFORMED_INPUT_SAFE_DASHBOARD_FIXTURE,
  CLEAN_LOW_RISK_REPORT_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_REPORT_FIXTURE,
  HIGH_RISK_MULTI_EVIDENCE_REPORT_FIXTURE,
  CE_SAFETY_BOUNDARY_REPORT_FIXTURE,
  DASHBOARD_READY_COMBINED_FIXTURE,
  REPORT_READY_COMBINED_FIXTURE,
  SERIALIZATION_PREVIEW_READY_COMBINED_FIXTURE,
  PHASE_35_COMPOSITE_EVIDENCE_DASHBOARD_FIXTURES,
  PHASE_35_COMPOSITE_EVIDENCE_REPORT_FIXTURES,
  PHASE_35_COMPOSITE_EVIDENCE_COMBINED_FIXTURES,
  listCompositeEvidenceDashboardReportFixtures,
  getCompositeEvidenceDashboardReportFixture,
  getCompositeEvidenceDashboardReportFixtureCapabilities,
} from './composite-evidence-fixtures/index.js';

// ─── Phase 40 strategy review dashboard fixtures ───────────────────────────────

export type {
  StrategyReviewDashboardFixture,
  StrategyReviewDashboardFixtureName,
  StrategyReviewDashboardFixtureKind,
  StrategyReviewMatrixReference,
  StrategyReviewPanelFixture,
  StrategyReviewCardFixture,
  StrategyReviewTableFixture,
  StrategyReviewTableRowFixture,
  StrategyReviewTableColumnFixture,
  StrategyReviewSummaryFixture,
  StrategyReviewSafetyBoundary,
  StrategyReviewValidationResult,
  StrategyReviewValidationIssue,
  StrategyReviewSafetyResult,
  StrategyReviewBuildInput,
  StrategyReviewBuildResult,
  StrategyReviewDashboardFixtureCapabilities,
} from './strategy-review-fixtures/index.js';

export {
  PHASE_40_STRATEGY_REVIEW_DASHBOARD_GENERATED_AT,
  PHASE_40_STRATEGY_REVIEW_DASHBOARD_SOURCE,
  STRATEGY_REVIEW_DASHBOARD_FIXTURE_NAMES,
  STRATEGY_REVIEW_DASHBOARD_FIXTURE_KINDS,
  buildStrategyReviewDashboardFixture,
  buildStrategyReviewSummary,
  normalizeStrategyReviewDashboardFixture,
  serializeStrategyReviewDashboardFixture,
  areStrategyReviewDashboardFixturesEqual,
  isStrategyReviewDashboardFixtureSerializable,
  validateStrategyReviewDashboardFixture,
  validateStrategyReviewDashboardSafety,
  getStrategyReviewDashboardFixtureCapabilities,
  DEFENSIVE_VS_AGGRESSIVE_REVIEW_DASHBOARD_FIXTURE,
  CREATOR_LED_REVIEW_DASHBOARD_FIXTURE,
  WALLET_LED_REVIEW_DASHBOARD_FIXTURE,
  MANIPULATION_AVOIDANCE_REVIEW_DASHBOARD_FIXTURE,
  NO_ACTION_SAFETY_REVIEW_DASHBOARD_FIXTURE,
  INSUFFICIENT_DATA_REVIEW_DASHBOARD_FIXTURE,
  HIGH_SCORE_POSITIVE_REVIEW_DASHBOARD_FIXTURE,
  HIGH_SCORE_FALSE_POSITIVE_REVIEW_DASHBOARD_FIXTURE,
  MISSED_OPPORTUNITY_REVIEW_DASHBOARD_FIXTURE,
  DRAWDOWN_CONTAINED_REVIEW_DASHBOARD_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_REVIEW_DASHBOARD_FIXTURE,
  FALSE_POSITIVE_PROTECTION_REVIEW_DASHBOARD_FIXTURE,
  MALFORMED_INPUT_SAFE_REVIEW_DASHBOARD_FIXTURE,
  DASHBOARD_READY_STRATEGY_REVIEW_FIXTURE,
  REPORT_READY_STRATEGY_REVIEW_FIXTURE,
  SAFETY_BOUNDARY_STRATEGY_REVIEW_FIXTURE,
  PHASE_40_STRATEGY_REVIEW_DASHBOARD_FIXTURES,
  listStrategyReviewDashboardFixtures,
  getStrategyReviewDashboardFixture,
} from './strategy-review-fixtures/index.js';

// ─── Phase 41 strategy review report fixtures ──────────────────────────────────

export type {
  StrategyReviewReportFixture,
  StrategyReviewReportFixtureName,
  StrategyReviewReportFixtureKind,
  StrategyReviewDashboardReference,
  StrategyReviewReportSectionFixture,
  StrategyReviewReportCardFixture,
  StrategyReviewReportTableFixture,
  StrategyReviewReportTableRowFixture,
  StrategyReviewReportTableColumnFixture,
  StrategyReviewReportSummaryFixture,
  StrategyReviewReportSafetyBoundary,
  StrategyReviewReportValidationResult,
  StrategyReviewReportValidationIssue,
  StrategyReviewReportSafetyResult,
  StrategyReviewReportBuildInput,
  StrategyReviewReportBuildResult,
  StrategyReviewReportFixtureCapabilities,
} from './strategy-review-reports/index.js';

export {
  PHASE_41_STRATEGY_REVIEW_REPORT_GENERATED_AT,
  PHASE_41_STRATEGY_REVIEW_REPORT_SOURCE,
  STRATEGY_REVIEW_REPORT_FIXTURE_NAMES,
  STRATEGY_REVIEW_REPORT_FIXTURE_KINDS,
  buildStrategyReviewReportFixture,
  buildStrategyReviewReportSummary,
  normalizeStrategyReviewReportFixture,
  serializeStrategyReviewReportFixture,
  areStrategyReviewReportFixturesEqual,
  isStrategyReviewReportFixtureSerializable,
  validateStrategyReviewReportFixture,
  validateStrategyReviewReportSafety,
  getStrategyReviewReportFixtureCapabilities,
  DEFENSIVE_VS_AGGRESSIVE_REVIEW_REPORT_FIXTURE,
  CREATOR_LED_REVIEW_REPORT_FIXTURE,
  WALLET_LED_REVIEW_REPORT_FIXTURE,
  MANIPULATION_AVOIDANCE_REVIEW_REPORT_FIXTURE,
  NO_ACTION_SAFETY_REVIEW_REPORT_FIXTURE,
  INSUFFICIENT_DATA_REVIEW_REPORT_FIXTURE,
  HIGH_SCORE_POSITIVE_REVIEW_REPORT_FIXTURE,
  HIGH_SCORE_FALSE_POSITIVE_REVIEW_REPORT_FIXTURE,
  MISSED_OPPORTUNITY_REVIEW_REPORT_FIXTURE,
  DRAWDOWN_CONTAINED_REVIEW_REPORT_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_REVIEW_REPORT_FIXTURE,
  FALSE_POSITIVE_PROTECTION_REVIEW_REPORT_FIXTURE,
  MALFORMED_INPUT_SAFE_REVIEW_REPORT_FIXTURE,
  DASHBOARD_READY_STRATEGY_REVIEW_REPORT_FIXTURE,
  SERIALIZATION_READY_STRATEGY_REVIEW_REPORT_FIXTURE,
  SAFETY_BOUNDARY_STRATEGY_REVIEW_REPORT_FIXTURE,
  PHASE_41_STRATEGY_REVIEW_REPORT_FIXTURES,
  listStrategyReviewReportFixtures,
  getStrategyReviewReportFixture,
} from './strategy-review-reports/index.js';
export {
  PHASE_42_STRATEGY_REVIEW_SERIALIZATION_GENERATED_AT,
  PHASE_42_STRATEGY_REVIEW_SERIALIZATION_SOURCE,
  STRATEGY_REVIEW_SERIALIZATION_PREVIEW_FIXTURE_NAMES,
  STRATEGY_REVIEW_SERIALIZATION_PREVIEW_FIXTURE_KINDS,
  STRATEGY_REVIEW_SERIALIZATION_PREVIEW_FORMATS,
  getStrategyReviewSerializationPreviewCapabilities,
  buildStrategyReviewSerializationPreviewFixture,
  buildStrategyReviewSerializationSummary,
  normalizeStrategyReviewSerializationPreviewFixture,
  serializeStrategyReviewSerializationPreviewFixture,
  areStrategyReviewSerializationPreviewFixturesEqual,
  isStrategyReviewSerializationPreviewFixtureSerializable,
  validateStrategyReviewSerializationPreviewFixture,
  validateStrategyReviewSerializationSafety,
  listStrategyReviewSerializationPreviewFixtures,
  getStrategyReviewSerializationPreviewFixture,
  DEFENSIVE_VS_AGGRESSIVE_JSON_PREVIEW_FIXTURE,
  CREATOR_LED_MARKDOWN_PREVIEW_FIXTURE,
  WALLET_LED_TEXT_PREVIEW_FIXTURE,
  MANIPULATION_AVOIDANCE_METADATA_PREVIEW_FIXTURE,
  NO_ACTION_SAFETY_JSON_PREVIEW_FIXTURE,
  INSUFFICIENT_DATA_MARKDOWN_PREVIEW_FIXTURE,
  HIGH_SCORE_POSITIVE_TEXT_PREVIEW_FIXTURE,
  HIGH_SCORE_FALSE_POSITIVE_METADATA_PREVIEW_FIXTURE,
  MISSED_OPPORTUNITY_JSON_PREVIEW_FIXTURE,
  DRAWDOWN_CONTAINED_MARKDOWN_PREVIEW_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_TEXT_PREVIEW_FIXTURE,
  FALSE_POSITIVE_PROTECTION_METADATA_PREVIEW_FIXTURE,
  MALFORMED_INPUT_SAFE_PREVIEW_FIXTURE as STRATEGY_REVIEW_MALFORMED_INPUT_SAFE_PREVIEW_FIXTURE,
  DASHBOARD_READY_SERIALIZATION_PREVIEW_FIXTURE,
  REPORT_READY_SERIALIZATION_PREVIEW_FIXTURE,
  SAFETY_BOUNDARY_SERIALIZATION_PREVIEW_FIXTURE,
  PHASE_42_STRATEGY_REVIEW_SERIALIZATION_PREVIEW_FIXTURES,
  PHASE_42_STRATEGY_REVIEW_SERIALIZATION_PREVIEW_FIXTURE_LIST,
  SERIALIZATION_NAME_TO_REPORT,
  SERIALIZATION_NAME_TO_KIND,
  SERIALIZATION_NAME_TO_FORMAT,
} from './strategy-review-serialization/index.js';


// ─── Phase 43 strategy review export planning fixtures ─────────────────────────

export type {
  StrategyReviewExportPlanFixture,
  StrategyReviewExportPlanFixtureName,
  StrategyReviewExportPlanFixtureKind,
  StrategyReviewExportPlanTarget,
  StrategyReviewSerializationPreviewReference,
  StrategyReviewExportFileExtension,
  StrategyReviewExportPlanDefinition,
  StrategyReviewExportPlanMeta,
  StrategyReviewExportPlanSafetyBoundary,
  StrategyReviewExportPlanSummary,
  StrategyReviewExportPlanValidationResult,
  StrategyReviewExportPlanValidationIssue,
  StrategyReviewExportPlanSafetyResult,
  StrategyReviewExportPlanBuildInput,
  StrategyReviewExportPlanBuildResult,
  StrategyReviewExportPlanCapabilities,
} from './strategy-review-export-planning/index.js';

export {
  PHASE_43_STRATEGY_REVIEW_EXPORT_PLAN_GENERATED_AT,
  PHASE_43_STRATEGY_REVIEW_EXPORT_PLAN_SOURCE,
  STRATEGY_REVIEW_EXPORT_PLAN_FIXTURE_NAMES,
  STRATEGY_REVIEW_EXPORT_PLAN_FIXTURE_KINDS,
  STRATEGY_REVIEW_EXPORT_PLAN_FORMAT_TARGETS,
  getStrategyReviewExportPlanCapabilities,
  buildStrategyReviewExportPlanFixture,
  buildStrategyReviewExportPlanSummary,
  normalizeStrategyReviewExportPlanFixture,
  serializeStrategyReviewExportPlanFixture,
  areStrategyReviewExportPlanFixturesEqual,
  isStrategyReviewExportPlanFixtureSerializable,
  validateStrategyReviewExportPlanFixture,
  validateStrategyReviewExportPlanSafety,
  listStrategyReviewExportPlanFixtures,
  getStrategyReviewExportPlanFixture,
  JSON_EXPORT_PLAN_DISABLED_FIXTURE,
  MARKDOWN_EXPORT_PLAN_DISABLED_FIXTURE,
  TEXT_EXPORT_PLAN_DISABLED_FIXTURE,
  METADATA_EXPORT_PLAN_DISABLED_FIXTURE,
  DEFENSIVE_VS_AGGRESSIVE_EXPORT_PLAN_FIXTURE,
  CREATOR_LED_EXPORT_PLAN_FIXTURE,
  WALLET_LED_EXPORT_PLAN_FIXTURE,
  MANIPULATION_AVOIDANCE_EXPORT_PLAN_FIXTURE,
  NO_ACTION_SAFETY_EXPORT_PLAN_FIXTURE,
  INSUFFICIENT_DATA_EXPORT_PLAN_FIXTURE,
  HIGH_SCORE_POSITIVE_EXPORT_PLAN_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_EXPORT_PLAN_FIXTURE,
  MALFORMED_INPUT_SAFE_EXPORT_PLAN_FIXTURE,
  DASHBOARD_READY_EXPORT_PLAN_FIXTURE,
  REPORT_READY_EXPORT_PLAN_FIXTURE,
  SAFETY_BOUNDARY_EXPORT_PLAN_FIXTURE,
  PHASE_43_STRATEGY_REVIEW_EXPORT_PLAN_FIXTURES,
  PHASE_43_STRATEGY_REVIEW_EXPORT_PLAN_FIXTURE_LIST,
  EXPORT_PLAN_NAME_TO_PREVIEW,
  EXPORT_PLAN_NAME_TO_KIND,
  EXPORT_PLAN_NAME_TO_TARGET,
} from './strategy-review-export-planning/index.js';

// Phase 44 — Strategy Review Export Queue Fixtures v1
export {
  PHASE_44_STRATEGY_REVIEW_EXPORT_QUEUE_GENERATED_AT,
  PHASE_44_STRATEGY_REVIEW_EXPORT_QUEUE_SOURCE,
  STRATEGY_REVIEW_EXPORT_QUEUE_FIXTURE_NAMES,
  STRATEGY_REVIEW_EXPORT_QUEUE_FIXTURE_KINDS,
  STRATEGY_REVIEW_EXPORT_QUEUE_STATES,
  STRATEGY_REVIEW_EXPORT_QUEUE_PRIORITIES,
  getStrategyReviewExportQueueCapabilities,
  buildStrategyReviewExportQueueFixture,
  buildStrategyReviewExportQueueSummary,
  listStrategyReviewExportQueueFixtures,
  getStrategyReviewExportQueueFixture,
  normalizeStrategyReviewExportQueueFixture,
  serializeStrategyReviewExportQueueFixture,
  areStrategyReviewExportQueueFixturesEqual,
  isStrategyReviewExportQueueFixtureSerializable,
  isValidStrategyReviewExportQueueFixtureName,
  isValidStrategyReviewExportQueueFixtureKind,
  isValidStrategyReviewExportQueueState,
  isValidStrategyReviewExportQueuePriority,
  isValidStrategyReviewExportQueueGeneratedAt,
  isValidStrategyReviewExportQueueSource,
  validateStrategyReviewExportQueueFixture,
  validateStrategyReviewExportQueueSafety,
  EXPORT_QUEUE_NAME_TO_KIND,
  EXPORT_QUEUE_NAME_TO_PLAN,
  EXPORT_QUEUE_NAME_TO_STATE,
  EXPORT_QUEUE_NAME_TO_PRIORITY,
  DEFENSIVE_VS_AGGRESSIVE_EXPORT_QUEUED_FIXTURE,
  CREATOR_LED_EXPORT_QUEUED_FIXTURE,
  WALLET_LED_EXPORT_QUEUED_FIXTURE,
  MANIPULATION_AVOIDANCE_EXPORT_QUEUED_FIXTURE,
  NO_ACTION_SAFETY_EXPORT_QUEUED_FIXTURE,
  INSUFFICIENT_DATA_EXPORT_QUEUED_FIXTURE,
  HIGH_SCORE_POSITIVE_EXPORT_QUEUED_FIXTURE,
  HIGH_SCORE_FALSE_POSITIVE_EXPORT_QUEUED_FIXTURE,
  MISSED_OPPORTUNITY_EXPORT_QUEUED_FIXTURE,
  DRAWDOWN_CONTAINED_EXPORT_QUEUED_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_EXPORT_QUEUED_FIXTURE,
  FALSE_POSITIVE_PROTECTION_EXPORT_QUEUED_FIXTURE,
  MALFORMED_INPUT_SAFE_EXPORT_QUEUED_FIXTURE,
  DASHBOARD_READY_EXPORT_QUEUE_FIXTURE,
  SERIALIZATION_READY_EXPORT_QUEUE_FIXTURE,
  SAFETY_BOUNDARY_EXPORT_QUEUE_FIXTURE,
  PHASE_44_STRATEGY_REVIEW_EXPORT_QUEUE_FIXTURES,
  PHASE_44_STRATEGY_REVIEW_EXPORT_QUEUE_FIXTURE_LIST,
} from './strategy-review-export-queue/index.js';

// Phase 45 — Strategy Review Export Audit Fixtures v1
export {
  PHASE_45_STRATEGY_REVIEW_EXPORT_AUDIT_GENERATED_AT,
  PHASE_45_STRATEGY_REVIEW_EXPORT_AUDIT_SOURCE,
  STRATEGY_REVIEW_EXPORT_AUDIT_FIXTURE_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_FIXTURE_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_STATES,
  STRATEGY_REVIEW_EXPORT_AUDIT_SEVERITIES,
  getStrategyReviewExportAuditCapabilities,
  buildStrategyReviewExportAuditFixture,
  buildStrategyReviewExportAuditSummary,
  listStrategyReviewExportAuditFixtures,
  getStrategyReviewExportAuditFixture,
  normalizeStrategyReviewExportAuditFixture,
  serializeStrategyReviewExportAuditFixture,
  areStrategyReviewExportAuditFixturesEqual,
  isStrategyReviewExportAuditFixtureSerializable,
  isValidStrategyReviewExportAuditFixtureName,
  isValidStrategyReviewExportAuditFixtureKind,
  isValidStrategyReviewExportAuditState,
  isValidStrategyReviewExportAuditSeverity,
  isValidStrategyReviewExportAuditGeneratedAt,
  isValidStrategyReviewExportAuditSource,
  validateStrategyReviewExportAuditFixture,
  validateStrategyReviewExportAuditSafety,
  EXPORT_AUDIT_NAME_TO_KIND,
  EXPORT_AUDIT_NAME_TO_QUEUE,
  EXPORT_AUDIT_NAME_TO_STATE,
  EXPORT_AUDIT_NAME_TO_SEVERITY,
  DEFENSIVE_VS_AGGRESSIVE_EXPORT_AUDITED_FIXTURE,
  CREATOR_LED_EXPORT_AUDITED_FIXTURE,
  WALLET_LED_EXPORT_AUDITED_FIXTURE,
  MANIPULATION_AVOIDANCE_EXPORT_AUDITED_FIXTURE,
  NO_ACTION_SAFETY_EXPORT_AUDITED_FIXTURE,
  INSUFFICIENT_DATA_EXPORT_AUDITED_FIXTURE,
  HIGH_SCORE_POSITIVE_EXPORT_AUDITED_FIXTURE,
  HIGH_SCORE_FALSE_POSITIVE_EXPORT_AUDITED_FIXTURE,
  MISSED_OPPORTUNITY_EXPORT_AUDITED_FIXTURE,
  DRAWDOWN_CONTAINED_EXPORT_AUDITED_FIXTURE,
  MIXED_SIGNAL_WATCHLIST_EXPORT_AUDITED_FIXTURE,
  FALSE_POSITIVE_PROTECTION_EXPORT_AUDITED_FIXTURE,
  MALFORMED_INPUT_SAFE_EXPORT_AUDITED_FIXTURE,
  DASHBOARD_READY_EXPORT_AUDIT_FIXTURE,
  SERIALIZATION_READY_EXPORT_AUDIT_FIXTURE,
  SAFETY_BOUNDARY_EXPORT_AUDIT_FIXTURE,
  PHASE_45_STRATEGY_REVIEW_EXPORT_AUDIT_FIXTURES,
  PHASE_45_STRATEGY_REVIEW_EXPORT_AUDIT_FIXTURE_LIST,
} from './strategy-review-export-audit/index.js';

// Phase 46 — Strategy Review Export Audit Report Fixtures v1
export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_PHASE,
  PHASE_46_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_GENERATED_AT,
  PHASE_46_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SOURCE,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_FIXTURE_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_FIXTURE_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_FIXTURES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_FIXTURE_MAP,
  listStrategyReviewExportAuditReportFixtures,
  getStrategyReviewExportAuditReportFixture,
  buildStrategyReviewExportAuditReportFixture,
  validateStrategyReviewExportAuditReportFixture,
  validateStrategyReviewExportAuditReportSafety,
  normalizeStrategyReviewExportAuditReportFixture,
  serializeStrategyReviewExportAuditReportFixture,
  areStrategyReviewExportAuditReportFixturesEqual,
  getStrategyReviewExportAuditReportCapabilities,
  isValidStrategyReviewExportAuditReportFixtureName,
  isValidStrategyReviewExportAuditReportFixtureKind,
  isValidStrategyReviewExportAuditReportState,
  isValidStrategyReviewExportAuditReportSeverity,
  isValidStrategyReviewExportAuditReportGeneratedAt,
  isValidStrategyReviewExportAuditReportSource,
} from './strategy-review-export-audit-report/index.js';

// Phase 47 — Strategy Review Export Audit Report View Models v1
export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_PHASE,
  PHASE_47_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_GENERATED_AT,
  PHASE_47_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_SOURCE,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODELS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_VIEW_MODEL_MAP,
  listStrategyReviewExportAuditReportViewModels,
  getStrategyReviewExportAuditReportViewModel,
  buildStrategyReviewExportAuditReportListItemViewModel,
  buildStrategyReviewExportAuditReportDetailViewModel,
  buildStrategyReviewExportAuditReportSummaryViewModel,
  buildStrategyReviewExportAuditReportViewModel,
  validateStrategyReviewExportAuditReportViewModel,
  validateStrategyReviewExportAuditReportViewModelSafety,
  normalizeStrategyReviewExportAuditReportViewModel,
  serializeStrategyReviewExportAuditReportViewModel,
  areStrategyReviewExportAuditReportViewModelsEqual,
  getStrategyReviewExportAuditReportViewModelCapabilities,
  isValidStrategyReviewExportAuditReportViewModelName,
  isValidStrategyReviewExportAuditReportViewModelKind,
  isValidStrategyReviewExportAuditReportViewModelStatus,
  isValidStrategyReviewExportAuditReportViewModelSeverity,
  isValidStrategyReviewExportAuditReportViewModelGeneratedAt,
  isValidStrategyReviewExportAuditReportViewModelSource,
} from './strategy-review-export-audit-report-view-models/index.js';

// ─── Phase 48 — Strategy Review Export Audit Report Read-Only API Contracts ────

export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_PHASE,
  PHASE_48_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_GENERATED_AT,
  PHASE_48_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SOURCE,
  PHASE_48_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_VERSION,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACTS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_LIST_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_DETAIL_API_CONTRACTS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_DETAIL_API_CONTRACT_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SUMMARY_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_NOT_FOUND_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_INVALID_ID_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_API_CONTRACTS,
  listStrategyReviewExportAuditReportApiContracts,
  getStrategyReviewExportAuditReportApiContract,
  getStrategyReviewExportAuditReportDetailApiContractByViewModelId,
  buildStrategyReviewExportAuditReportListApiContract,
  buildStrategyReviewExportAuditReportDetailApiContract,
  buildStrategyReviewExportAuditReportSummaryApiContract,
  buildStrategyReviewExportAuditReportErrorApiContract,
  buildStrategyReviewExportAuditReportApiContract,
  validateStrategyReviewExportAuditReportApiContract,
  validateStrategyReviewExportAuditReportApiContractSafety,
  normalizeStrategyReviewExportAuditReportApiContract,
  serializeStrategyReviewExportAuditReportApiContract,
  areStrategyReviewExportAuditReportApiContractsEqual,
  getStrategyReviewExportAuditReportApiContractCapabilities,
  isValidStrategyReviewExportAuditReportApiContractName,
  isValidStrategyReviewExportAuditReportApiContractKind,
  isValidStrategyReviewExportAuditReportApiContractGeneratedAt,
  isValidStrategyReviewExportAuditReportApiContractSource,
  stableDeterministicContractChecksum,
} from './strategy-review-export-audit-report-contracts/index.js';


// ─── Phase 49 — Strategy Review Export Audit Report API Contract Selectors ─────

export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_PHASE,
  PHASE_49_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_GENERATED_AT,
  PHASE_49_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_SOURCE,
  PHASE_49_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_VERSION,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTORS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_API_CONTRACT_SELECTOR_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_LIST_API_CONTRACT_SELECTOR,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_DETAIL_API_CONTRACT_SELECTORS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_DETAIL_API_CONTRACT_SELECTOR_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SUMMARY_API_CONTRACT_SELECTOR,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_NOT_FOUND_API_CONTRACT_SELECTOR,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_INVALID_ID_API_CONTRACT_SELECTOR,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_API_CONTRACT_SELECTORS,
  listStrategyReviewExportAuditReportApiContractSelectors,
  getStrategyReviewExportAuditReportApiContractSelector,
  selectStrategyReviewExportAuditReportListApiContract,
  selectStrategyReviewExportAuditReportDetailApiContract,
  selectStrategyReviewExportAuditReportSummaryApiContract,
  selectStrategyReviewExportAuditReportErrorApiContract,
  buildStrategyReviewExportAuditReportApiContractSelectorQuery,
  buildStrategyReviewExportAuditReportApiContractSelectorResult,
  buildStrategyReviewExportAuditReportApiContractSelectorFixture,
  validateStrategyReviewExportAuditReportApiContractSelector,
  validateStrategyReviewExportAuditReportApiContractSelectorResult,
  validateStrategyReviewExportAuditReportApiContractSelectorSafety,
  normalizeStrategyReviewExportAuditReportApiContractSelector,
  serializeStrategyReviewExportAuditReportApiContractSelector,
  areStrategyReviewExportAuditReportApiContractSelectorsEqual,
  getStrategyReviewExportAuditReportApiContractSelectorCapabilities,
  isValidStrategyReviewExportAuditReportApiContractSelectorName,
  isValidStrategyReviewExportAuditReportApiContractSelectorKind,
  isValidStrategyReviewExportAuditReportApiContractSelectorGeneratedAt,
  isValidStrategyReviewExportAuditReportApiContractSelectorSource,
  stableDeterministicSelectorChecksum,
} from './strategy-review-export-audit-report-contract-selectors/index.js';

// ─── Phase 50 — Strategy Review Export Audit Report Selector View Models ───────

export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_PHASE,
  PHASE_50_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_GENERATED_AT,
  PHASE_50_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_SOURCE,
  PHASE_50_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_VERSION,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODELS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_LIST_SELECTOR_VIEW_MODEL,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_DETAIL_SELECTOR_VIEW_MODELS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SUMMARY_SELECTOR_VIEW_MODEL,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_ERROR_SELECTOR_VIEW_MODELS,
  listStrategyReviewExportAuditReportSelectorViewModels,
  getStrategyReviewExportAuditReportSelectorViewModel,
  buildStrategyReviewExportAuditReportSelectorViewModel,
  buildStrategyReviewExportAuditReportSelectorListViewModel,
  buildStrategyReviewExportAuditReportSelectorDetailViewModel,
  buildStrategyReviewExportAuditReportSelectorSummaryViewModel,
  buildStrategyReviewExportAuditReportSelectorErrorViewModel,
  validateStrategyReviewExportAuditReportSelectorViewModel,
  validateStrategyReviewExportAuditReportSelectorViewModelSafety,
  normalizeStrategyReviewExportAuditReportSelectorViewModel,
  serializeStrategyReviewExportAuditReportSelectorViewModel,
  areStrategyReviewExportAuditReportSelectorViewModelsEqual,
  getStrategyReviewExportAuditReportSelectorViewModelCapabilities,
  isValidStrategyReviewExportAuditReportSelectorViewModelName,
  isValidStrategyReviewExportAuditReportSelectorViewModelKind,
  isValidStrategyReviewExportAuditReportSelectorViewModelGeneratedAt,
  isValidStrategyReviewExportAuditReportSelectorViewModelSource,
  stableDeterministicSelectorViewModelChecksum,
} from './strategy-review-export-audit-report-selector-view-models/index.js';

// ─── Phase 51 — Strategy Review Export Audit Report Selector View Model API Contracts ─────

export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_PHASE,
  PHASE_51_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_GENERATED_AT,
  PHASE_51_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_SOURCE,
  PHASE_51_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_VERSION,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACTS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_API_CONTRACT_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_LIST_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_DETAIL_API_CONTRACTS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_DETAIL_API_CONTRACT_MAP,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_SUMMARY_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_ERROR_NOT_FOUND_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_ERROR_INVALID_ID_API_CONTRACT,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SELECTOR_VIEW_MODEL_ERROR_API_CONTRACTS,
  listStrategyReviewExportAuditReportSelectorViewModelApiContracts,
  getStrategyReviewExportAuditReportSelectorViewModelApiContract,
  getStrategyReviewExportAuditReportSelectorViewModelDetailApiContractBySourceViewModelId,
  buildStrategyReviewExportAuditReportSelectorViewModelApiContract,
  buildStrategyReviewExportAuditReportSelectorViewModelListApiContract,
  buildStrategyReviewExportAuditReportSelectorViewModelDetailApiContract,
  buildStrategyReviewExportAuditReportSelectorViewModelSummaryApiContract,
  buildStrategyReviewExportAuditReportSelectorViewModelErrorApiContract,
  validateStrategyReviewExportAuditReportSelectorViewModelApiContract,
  validateStrategyReviewExportAuditReportSelectorViewModelApiContractSafety,
  normalizeStrategyReviewExportAuditReportSelectorViewModelApiContract,
  serializeStrategyReviewExportAuditReportSelectorViewModelApiContract,
  areStrategyReviewExportAuditReportSelectorViewModelApiContractsEqual,
  getStrategyReviewExportAuditReportSelectorViewModelApiContractCapabilities,
  isValidStrategyReviewExportAuditReportSelectorViewModelApiContractName,
  isValidStrategyReviewExportAuditReportSelectorViewModelApiContractKind,
  isValidStrategyReviewExportAuditReportSelectorViewModelApiContractGeneratedAt,
  isValidStrategyReviewExportAuditReportSelectorViewModelApiContractSource,
  stableDeterministicSelectorViewModelApiContractChecksum,
} from './strategy-review-export-audit-report-selector-view-model-contracts/index.js';

// ─── Phase 52 — Strategy Review Export Audit Report Surface Registry ─────

export {
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_PHASE,
  PHASE_52_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_GENERATED_AT,
  PHASE_52_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_SOURCE,
  PHASE_52_STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_VERSION,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_ENTRY_NAMES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_ENTRY_KINDS,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_ENTRIES,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY,
  STRATEGY_REVIEW_EXPORT_AUDIT_REPORT_SURFACE_REGISTRY_MAP,
  listStrategyReviewExportAuditReportSurfaceRegistryEntries,
  getStrategyReviewExportAuditReportSurfaceRegistryEntry,
  buildStrategyReviewExportAuditReportSurfaceRegistry,
  buildStrategyReviewExportAuditReportSurfaceRegistryEntry,
  validateStrategyReviewExportAuditReportSurfaceRegistry,
  validateStrategyReviewExportAuditReportSurfaceRegistrySafety,
  normalizeStrategyReviewExportAuditReportSurfaceRegistry,
  serializeStrategyReviewExportAuditReportSurfaceRegistry,
  areStrategyReviewExportAuditReportSurfaceRegistriesEqual,
  getStrategyReviewExportAuditReportSurfaceRegistryCapabilities,
  isValidStrategyReviewExportAuditReportSurfaceRegistryEntryName,
  isValidStrategyReviewExportAuditReportSurfaceRegistryEntryKind,
  isValidStrategyReviewExportAuditReportSurfaceRegistryGeneratedAt,
  isValidStrategyReviewExportAuditReportSurfaceRegistrySource,
  stableDeterministicStrategyReviewExportAuditReportSurfaceRegistryChecksum,
} from './strategy-review-export-audit-report-surface-registry/index.js';

// ─── Phase 53 — Synthetic Launch Intelligence Foundation ─────

export {
  SYNTHETIC_LAUNCH_INTELLIGENCE_PHASE,
  PHASE_53_SYNTHETIC_LAUNCH_INTELLIGENCE_GENERATED_AT,
  PHASE_53_SYNTHETIC_LAUNCH_INTELLIGENCE_SOURCE,
  PHASE_53_SYNTHETIC_LAUNCH_INTELLIGENCE_VERSION,
  SYNTHETIC_LAUNCH_INTELLIGENCE_SCENARIO_NAMES,
  SYNTHETIC_LAUNCH_INTELLIGENCE_SCENARIO_KINDS,
  SYNTHETIC_LAUNCH_INTELLIGENCE_FIXTURES,
  SYNTHETIC_LAUNCH_INTELLIGENCE_FIXTURE_MAP,
  listSyntheticLaunchIntelligenceFixtures,
  getSyntheticLaunchIntelligenceFixture,
  buildSyntheticLaunchIntelligenceFixture,
  buildSyntheticLaunchIntelligenceViewModel,
  buildSyntheticLaunchIntelligenceApiContract,
  selectSyntheticLaunchIntelligenceFixture,
  validateSyntheticLaunchIntelligenceFixture,
  validateSyntheticLaunchIntelligenceSafety,
  normalizeSyntheticLaunchIntelligenceFixture,
  serializeSyntheticLaunchIntelligenceFixture,
  areSyntheticLaunchIntelligenceFixturesEqual,
  getSyntheticLaunchIntelligenceCapabilities,
  stableDeterministicSyntheticLaunchIntelligenceChecksum,
  isValidSyntheticLaunchIntelligenceScenarioName,
  isValidSyntheticLaunchIntelligenceScenarioKind,
  isValidSyntheticLaunchIntelligenceGeneratedAt,
  isValidSyntheticLaunchIntelligenceSource,
} from './synthetic-launch-intelligence/index.js';

// ─── Phase 54 — Read-Only Provider Interface Contracts ────────

export {
  READ_ONLY_PROVIDER_CONTRACTS_PHASE,
  PHASE_54_READ_ONLY_PROVIDER_CONTRACTS_GENERATED_AT,
  PHASE_54_READ_ONLY_PROVIDER_CONTRACTS_SOURCE,
  PHASE_54_READ_ONLY_PROVIDER_CONTRACTS_VERSION,
  READ_ONLY_PROVIDER_CONTRACT_NAMES,
  READ_ONLY_PROVIDER_CONTRACT_KINDS,
  READ_ONLY_PROVIDER_CONTRACT_FIXTURES,
  READ_ONLY_PROVIDER_CONTRACT_FIXTURE_MAP,
  listReadOnlyProviderContractFixtures,
  getReadOnlyProviderContractFixture,
  buildReadOnlyProviderContractFixture,
  buildReadOnlyProviderContractViewModel,
  buildReadOnlyProviderApiContract,
  selectReadOnlyProviderContractFixture,
  validateReadOnlyProviderContractFixture,
  validateReadOnlyProviderContractSafety,
  normalizeReadOnlyProviderContractFixture,
  serializeReadOnlyProviderContractFixture,
  areReadOnlyProviderContractFixturesEqual,
  getReadOnlyProviderContractCapabilities,
  stableDeterministicReadOnlyProviderContractChecksum,
  isValidReadOnlyProviderContractName,
  isValidReadOnlyProviderContractKind,
  isValidReadOnlyProviderContractGeneratedAt,
  isValidReadOnlyProviderContractSource,
} from './read-only-provider-contracts/index.js';


// ─── Phase 55 — Read-Only Provider Adapter Mocks ──────────────

export {
  READ_ONLY_PROVIDER_ADAPTER_MOCKS_PHASE,
  PHASE_55_READ_ONLY_PROVIDER_ADAPTER_MOCKS_GENERATED_AT,
  PHASE_55_READ_ONLY_PROVIDER_ADAPTER_MOCKS_SOURCE,
  PHASE_55_READ_ONLY_PROVIDER_ADAPTER_MOCKS_VERSION,
  READ_ONLY_PROVIDER_ADAPTER_MOCK_NAMES,
  READ_ONLY_PROVIDER_ADAPTER_MOCK_KINDS,
  READ_ONLY_PROVIDER_ADAPTER_MOCK_FIXTURES,
  READ_ONLY_PROVIDER_ADAPTER_MOCK_FIXTURE_MAP,
  listReadOnlyProviderAdapterMockFixtures,
  getReadOnlyProviderAdapterMockFixture,
  buildReadOnlyProviderAdapterMockFixture,
  buildReadOnlyProviderAdapterMockViewModel,
  buildReadOnlyProviderAdapterMockApiContract,
  selectReadOnlyProviderAdapterMockFixture,
  runReadOnlyProviderAdapterMock,
  validateReadOnlyProviderAdapterMockFixture,
  validateReadOnlyProviderAdapterMockSafety,
  normalizeReadOnlyProviderAdapterMockFixture,
  serializeReadOnlyProviderAdapterMockFixture,
  areReadOnlyProviderAdapterMockFixturesEqual,
  getReadOnlyProviderAdapterMockCapabilities,
  stableDeterministicReadOnlyProviderAdapterMockChecksum,
  isValidReadOnlyProviderAdapterMockName,
  isValidReadOnlyProviderAdapterMockKind,
  isValidReadOnlyProviderAdapterMockGeneratedAt,
  isValidReadOnlyProviderAdapterMockSource,
} from './read-only-provider-adapter-mocks/index.js';

// ─── Phase 56 — Synthetic Event Stream Lifecycle ──────────────

export {
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_PHASE,
  PHASE_56_SYNTHETIC_EVENT_STREAM_LIFECYCLE_GENERATED_AT,
  PHASE_56_SYNTHETIC_EVENT_STREAM_LIFECYCLE_SOURCE,
  PHASE_56_SYNTHETIC_EVENT_STREAM_LIFECYCLE_VERSION,
  PHASE_56_SYNTHETIC_EVENT_STREAM_LIFECYCLE_SCHEMA_VERSION,
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_STREAM_NAMES,
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_STREAM_KINDS,
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_EVENT_KINDS,
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_FIXTURES,
  SYNTHETIC_EVENT_STREAM_LIFECYCLE_FIXTURE_MAP,
  listSyntheticEventStreamLifecycleFixtures,
  getSyntheticEventStreamLifecycleFixture,
  buildSyntheticEventStreamLifecycleFixture,
  buildSyntheticEventStreamLifecycleViewModel,
  buildSyntheticEventStreamLifecycleApiContract,
  selectSyntheticEventStreamLifecycleFixture,
  selectSyntheticEventStreamLifecycleEvents,
  selectSyntheticEventStreamLifecycleDerivedState,
  selectSyntheticEventStreamLifecycleViewModel,
  selectSyntheticEventStreamLifecycleApiSummary,
  reduceSyntheticEventStreamLifecycle,
  validateSyntheticEventStreamLifecycleFixture,
  validateSyntheticEventStreamLifecycleSafety,
  normalizeSyntheticEventStreamLifecycleFixture,
  serializeSyntheticEventStreamLifecycleFixture,
  areSyntheticEventStreamLifecycleFixturesEqual,
  getSyntheticEventStreamLifecycleCapabilities,
  stableDeterministicSyntheticEventStreamLifecycleChecksum,
  isValidSyntheticEventStreamLifecycleStreamName,
  isValidSyntheticEventStreamLifecycleStreamKind,
  isValidSyntheticEventStreamLifecycleGeneratedAt,
  isValidSyntheticEventStreamLifecycleSource,
  isValidSyntheticEventStreamLifecycleSchemaVersion,
} from './synthetic-event-stream-lifecycle/index.js';

// ─── Phase 57 — Synthetic Event Stream Replay Harness ──────────────

export {
  SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_PHASE,
  PHASE_57_SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_GENERATED_AT,
  PHASE_57_SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_SOURCE,
  PHASE_57_SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_VERSION,
  PHASE_57_SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_SCHEMA_VERSION,
  SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_SCENARIO_NAMES,
  SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_SCENARIO_KINDS,
  SYNTHETIC_EVENT_STREAM_REPLAY_MISMATCH_KINDS,
  SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_FIXTURES,
  SYNTHETIC_EVENT_STREAM_REPLAY_HARNESS_FIXTURE_MAP,
  listSyntheticEventStreamReplayHarnessFixtures,
  getSyntheticEventStreamReplayHarnessFixture,
  buildSyntheticEventStreamReplayHarnessFixture,
  buildSyntheticEventStreamReplayClock,
  buildSyntheticEventStreamReplayStep,
  buildSyntheticEventStreamReplaySnapshot,
  buildSyntheticEventStreamReplayReport,
  runSyntheticEventStreamReplayHarness,
  compareSyntheticEventStreamReplaySnapshots,
  buildSyntheticEventStreamReplayHarnessViewModel,
  buildSyntheticEventStreamReplayHarnessApiContract,
  selectSyntheticEventStreamReplayHarnessFixture,
  validateSyntheticEventStreamReplayHarnessFixture,
  validateSyntheticEventStreamReplayHarnessSafety,
  normalizeSyntheticEventStreamReplayHarnessFixture,
  serializeSyntheticEventStreamReplayHarnessFixture,
  areSyntheticEventStreamReplayHarnessFixturesEqual,
  getSyntheticEventStreamReplayHarnessCapabilities,
} from './synthetic-event-stream-replay-harness/index.js';

// ─── Phase 58 — Launch Risk Engine ────────────────────────────────────────────

export {
  LAUNCH_RISK_ENGINE_PHASE,
  PHASE_58_LAUNCH_RISK_ENGINE_GENERATED_AT,
  PHASE_58_LAUNCH_RISK_ENGINE_SOURCE,
  PHASE_58_LAUNCH_RISK_ENGINE_VERSION,
  PHASE_58_LAUNCH_RISK_ENGINE_SCHEMA_VERSION,
  LAUNCH_RISK_ENGINE_ASSESSMENT_NAMES,
  LAUNCH_RISK_ENGINE_ASSESSMENT_KINDS,
  LAUNCH_RISK_FACTOR_KINDS,
  LAUNCH_RISK_SEVERITY_VALUES,
  LAUNCH_RISK_CONFIDENCE_LABELS,
  LAUNCH_RISK_BANDS,
  LAUNCH_RISK_ENGINE_FIXTURES,
  LAUNCH_RISK_ENGINE_FIXTURE_MAP,
  LAUNCH_RISK_ENGINE_DEFAULT_THRESHOLDS,
  listLaunchRiskEngineFixtures,
  getLaunchRiskEngineFixture,
  buildLaunchRiskEngineFixture,
  buildLaunchRiskFactorOutput,
  buildLaunchRiskAssessment,
  calculateLaunchRiskScore,
  classifyLaunchRiskBand,
  buildLaunchRiskEngineViewModel,
  buildLaunchRiskEngineApiContract,
  selectLaunchRiskEngineFixture,
  selectLaunchRiskEngineFactorOutputs,
  selectLaunchRiskEngineAssessment,
  selectLaunchRiskEngineViewModel,
  selectLaunchRiskEngineApiSummary,
  validateLaunchRiskEngineFixture,
  validateLaunchRiskEngineSafety,
  validateLaunchRiskEngineFixtureTable,
  normalizeLaunchRiskEngineFixture,
  serializeLaunchRiskEngineFixture,
  areLaunchRiskEngineFixturesEqual,
  getLaunchRiskEngineCapabilities,
  stableDeterministicLaunchRiskEngineChecksum,
  isValidLaunchRiskEngineAssessmentName,
  isValidLaunchRiskEngineAssessmentKind,
  isValidLaunchRiskEngineGeneratedAt,
  isValidLaunchRiskEngineSource,
  isValidLaunchRiskEngineSchemaVersion,
} from './launch-risk-engine/index.js';

// ─── Phase 59 — Risk Explanation and Evidence Models ───────────────────────────

export {
  RISK_EXPLANATION_EVIDENCE_PHASE,
  PHASE_59_RISK_EXPLANATION_EVIDENCE_GENERATED_AT,
  PHASE_59_RISK_EXPLANATION_EVIDENCE_SOURCE,
  PHASE_59_RISK_EXPLANATION_EVIDENCE_VERSION,
  PHASE_59_RISK_EXPLANATION_EVIDENCE_SCHEMA_VERSION,
  RISK_EXPLANATION_EVIDENCE_NAMES,
  RISK_EXPLANATION_EVIDENCE_KINDS,
  RISK_EVIDENCE_NODE_KINDS,
  RISK_EVIDENCE_EDGE_KINDS,
  RISK_EXPLANATION_TEMPLATES,
  RISK_EXPLANATION_EVIDENCE_FIXTURES,
  RISK_EXPLANATION_EVIDENCE_FIXTURE_MAP,
  listRiskExplanationEvidenceFixtures,
  getRiskExplanationEvidenceFixture,
  buildRiskExplanationEvidenceFixture,
  buildRiskEvidenceNode,
  buildRiskEvidenceEdge,
  buildRiskEvidenceGraph,
  buildRiskExplanationFromTemplate,
  buildRiskExplanationEvidenceViewModel,
  buildRiskExplanationEvidenceApiContract,
  selectRiskExplanationEvidenceFixture,
  validateRiskExplanationEvidenceFixture,
  validateRiskExplanationEvidenceSafety,
  normalizeRiskExplanationEvidenceFixture,
  serializeRiskExplanationEvidenceFixture,
  areRiskExplanationEvidenceFixturesEqual,
  getRiskExplanationEvidenceCapabilities,
} from './risk-explanation-evidence/index.js';

// ─── Phase 60 — Paper Sniper Simulation Foundation ─────────────────────────────

export {
  PAPER_SNIPER_SIMULATION_PHASE,
  PHASE_60_PAPER_SNIPER_SIMULATION_GENERATED_AT,
  PHASE_60_PAPER_SNIPER_SIMULATION_SOURCE,
  PHASE_60_PAPER_SNIPER_SIMULATION_VERSION,
  PHASE_60_PAPER_SNIPER_SIMULATION_SCHEMA_VERSION,
  PAPER_SNIPER_SIMULATION_NAMES,
  PAPER_SNIPER_SIMULATION_KINDS,
  PAPER_SNIPER_MARKET_LIQUIDITY_BUCKETS,
  PAPER_SNIPER_MARKET_VOLATILITY_BUCKETS,
  PAPER_SNIPER_LATENCY_BUCKETS,
  PAPER_SNIPER_SLIPPAGE_BUCKETS,
  PAPER_SNIPER_FAILURE_BUCKETS,
  PAPER_SNIPER_SIMULATION_FIXTURES,
  PAPER_SNIPER_SIMULATION_FIXTURE_MAP,
  listPaperSniperSimulationFixtures,
  getPaperSniperSimulationFixture,
  buildPaperSniperSimulationFixture,
  buildPaperSniperMarketModel,
  buildPaperSniperLatencyModel,
  buildPaperSniperSlippageModel,
  buildPaperSniperFailureModel,
  runPaperSniperSimulation,
  buildPaperSniperSimulationOutcomesSummary,
  buildPaperSniperSimulationViewModel,
  buildPaperSniperSimulationApiContract,
  selectPaperSniperSimulationFixture,
  selectPaperSniperSimulationOutcome,
  selectPaperSniperSimulationViewModel,
  selectPaperSniperSimulationApiSummary,
  validatePaperSniperSimulationFixture,
  validatePaperSniperSimulationSafety,
  normalizePaperSniperSimulationFixture,
  serializePaperSniperSimulationFixture,
  arePaperSniperSimulationFixturesEqual,
  stableDeterministicPaperSniperSimulationChecksum,
  isValidPaperSniperSimulationName,
  isValidPaperSniperSimulationKind,
  isValidPaperSniperSimulationGeneratedAt,
  isValidPaperSniperSimulationSource,
  isValidPaperSniperSimulationSchemaVersion,
  getPaperSniperSimulationCapabilities,
} from './paper-sniper-simulation/index.js';

// ─── Phase 61 — Paper Execution Quality Metrics ─────────────────────────────────

export {
  PAPER_EXECUTION_QUALITY_METRICS_PHASE,
  PHASE_61_PAPER_EXECUTION_QUALITY_METRICS_GENERATED_AT,
  PHASE_61_PAPER_EXECUTION_QUALITY_METRICS_SOURCE,
  PHASE_61_PAPER_EXECUTION_QUALITY_METRICS_VERSION,
  PHASE_61_PAPER_EXECUTION_QUALITY_METRICS_SCHEMA_VERSION,
  PAPER_EXECUTION_QUALITY_METRIC_NAMES,
  PAPER_EXECUTION_QUALITY_METRIC_KINDS,
  PAPER_EXECUTION_LATENCY_BUCKETS,
  PAPER_EXECUTION_OBSERVATION_DELAY_BUCKETS,
  PAPER_EXECUTION_SUBMISSION_DELAY_BUCKETS,
  PAPER_EXECUTION_CONFIRMATION_DELAY_BUCKETS,
  PAPER_EXECUTION_LATENCY_QUALITY_LABELS,
  PAPER_EXECUTION_FILL_STATUSES,
  PAPER_EXECUTION_FILL_QUALITY_LABELS,
  PAPER_EXECUTION_MISSED_ENTRY_CLASSIFICATIONS,
  PAPER_EXECUTION_SLIPPAGE_BUCKETS,
  PAPER_EXECUTION_PRICE_IMPACT_BUCKETS,
  PAPER_EXECUTION_LIQUIDITY_SENSITIVITY_LABELS,
  PAPER_EXECUTION_SLIPPAGE_QUALITY_LABELS,
  PAPER_EXECUTION_REJECTION_TAXONOMY_KINDS,
  PAPER_EXECUTION_QUALITY_BANDS,
  PAPER_EXECUTION_QUALITY_METRIC_FIXTURES,
  PAPER_EXECUTION_QUALITY_METRIC_FIXTURE_MAP,
  listPaperExecutionQualityMetricFixtures,
  getPaperExecutionQualityMetricFixture,
  buildPaperExecutionQualityMetricFixture,
  buildPaperLatencyMetrics,
  buildPaperFillQualityMetrics,
  buildPaperSlippageMetrics,
  buildPaperRejectionMetrics,
  buildPaperExecutionQualityScorecard,
  aggregatePaperExecutionQualityMetrics,
  buildPaperExecutionQualityMetricsViewModel,
  buildPaperExecutionQualityMetricsApiContract,
  selectPaperExecutionQualityMetricFixture,
  selectPaperExecutionQualityScorecard,
  selectPaperExecutionQualityAggregateSummary,
  selectPaperExecutionQualityMetricsViewModel,
  selectPaperExecutionQualityMetricsApiSummary,
  validatePaperExecutionQualityMetricFixture,
  validatePaperExecutionQualityMetricsSafety,
  normalizePaperExecutionQualityMetricFixture,
  serializePaperExecutionQualityMetricFixture,
  arePaperExecutionQualityMetricFixturesEqual,
  stableDeterministicPaperExecutionQualityMetricsChecksum,
  isValidPaperExecutionQualityMetricName,
  isValidPaperExecutionQualityMetricKind,
  isValidPaperExecutionQualityMetricsGeneratedAt,
  isValidPaperExecutionQualityMetricsSource,
  isValidPaperExecutionQualityMetricsSchemaVersion,
  getPaperExecutionQualityMetricsCapabilities,
} from './paper-execution-quality-metrics/index.js';

// ─── Phase 62 — Synthetic Strategy Comparison Lab ──────────────────────────────

export {
  SYNTHETIC_STRATEGY_COMPARISON_LAB_PHASE,
  PHASE_62_SYNTHETIC_STRATEGY_COMPARISON_LAB_GENERATED_AT,
  PHASE_62_SYNTHETIC_STRATEGY_COMPARISON_LAB_SOURCE,
  PHASE_62_SYNTHETIC_STRATEGY_COMPARISON_LAB_VERSION,
  PHASE_62_SYNTHETIC_STRATEGY_COMPARISON_LAB_SCHEMA_VERSION,
  SYNTHETIC_STRATEGY_COMPARISON_LAB_NAMES,
  SYNTHETIC_STRATEGY_COMPARISON_LAB_KINDS,
  SYNTHETIC_STRATEGY_VARIANT_IDS,
  SYNTHETIC_STRATEGY_SENSITIVITY_WARNING_KINDS,
  SYNTHETIC_STRATEGY_COMPARISON_QUALITY_BANDS,
  SYNTHETIC_STRATEGY_COMPARISON_LAB_FIXTURES,
  SYNTHETIC_STRATEGY_COMPARISON_LAB_FIXTURE_MAP,
  listSyntheticStrategyComparisonLabFixtures,
  getSyntheticStrategyComparisonLabFixture,
  buildSyntheticStrategyComparisonLabFixture,
  buildSyntheticStrategyVariant,
  buildSyntheticStrategyScenarioMatrix,
  buildSyntheticStrategyComparisonRun,
  buildSyntheticStrategyComparisonScorecard,
  buildSyntheticStrategyComparisonAggregate,
  buildSyntheticStrategyComparisonLabViewModel,
  buildSyntheticStrategyComparisonLabApiContract,
  selectSyntheticStrategyComparisonLabFixture,
  validateSyntheticStrategyComparisonLabFixture,
  validateSyntheticStrategyComparisonLabSafety,
  normalizeSyntheticStrategyComparisonLabFixture,
  serializeSyntheticStrategyComparisonLabFixture,
  areSyntheticStrategyComparisonLabFixturesEqual,
  stableDeterministicSyntheticStrategyComparisonLabChecksum,
  getSyntheticStrategyComparisonLabCapabilities,
  isValidSyntheticStrategyComparisonLabName,
  isValidSyntheticStrategyComparisonLabKind,
  isValidSyntheticStrategyComparisonLabGeneratedAt,
  isValidSyntheticStrategyComparisonLabSource,
  isValidSyntheticStrategyComparisonLabSchemaVersion,
} from './synthetic-strategy-comparison-lab/index.js';

// ─── Phase 63 — Read-Only Provider Adapter Gate ───────────────────────────────

export {
  READ_ONLY_PROVIDER_ADAPTER_GATE_PHASE,
  PHASE_63_READ_ONLY_PROVIDER_ADAPTER_GATE_GENERATED_AT,
  PHASE_63_READ_ONLY_PROVIDER_ADAPTER_GATE_SOURCE,
  PHASE_63_READ_ONLY_PROVIDER_ADAPTER_GATE_VERSION,
  PHASE_63_READ_ONLY_PROVIDER_ADAPTER_GATE_SCHEMA_VERSION,
  READ_ONLY_PROVIDER_ADAPTER_GATE_NAMES,
  READ_ONLY_PROVIDER_ADAPTER_GATE_KINDS,
  READ_ONLY_PROVIDER_GATE_POLICY_KINDS,
  READ_ONLY_PROVIDER_GATE_STATE_KINDS,
  READ_ONLY_PROVIDER_ADAPTER_GATE_FIXTURES,
  READ_ONLY_PROVIDER_ADAPTER_GATE_FIXTURE_MAP,
  listReadOnlyProviderAdapterGateFixtures,
  getReadOnlyProviderAdapterGateFixture,
  buildReadOnlyProviderAdapterGateFixture,
  buildReadOnlyProviderGatePolicy,
  buildReadOnlyProviderGateState,
  buildReadOnlyProviderResolutionResult,
  buildReadOnlyProviderCapabilityCheck,
  buildReadOnlyProviderCompatibilityCheck,
  buildReadOnlyProviderGateReport,
  buildReadOnlyProviderAdapterGateViewModel,
  buildReadOnlyProviderAdapterGateApiContract,
  selectReadOnlyProviderAdapterGateFixture,
  validateReadOnlyProviderAdapterGateFixture,
  validateReadOnlyProviderAdapterGateSafety,
  normalizeReadOnlyProviderAdapterGateFixture,
  serializeReadOnlyProviderAdapterGateFixture,
  areReadOnlyProviderAdapterGateFixturesEqual,
  getReadOnlyProviderAdapterGateCapabilities,
  stableDeterministicReadOnlyProviderAdapterGateChecksum,
  isValidReadOnlyProviderAdapterGateName,
  isValidReadOnlyProviderAdapterGateKind,
  isValidReadOnlyProviderAdapterGatePolicyKind,
  isValidReadOnlyProviderAdapterGateStateKind,
  isValidReadOnlyProviderAdapterGateGeneratedAt,
  isValidReadOnlyProviderAdapterGateSource,
  isValidReadOnlyProviderAdapterGateSchemaVersion,
} from './read-only-provider-adapter-gate/index.js';

// ─── Phase 64 — Read-Only Solana Provider Boundary ────────────────────────────

export {
  READ_ONLY_SOLANA_PROVIDER_BOUNDARY_PHASE,
  PHASE_64_READ_ONLY_SOLANA_PROVIDER_BOUNDARY_GENERATED_AT,
  PHASE_64_READ_ONLY_SOLANA_PROVIDER_BOUNDARY_SOURCE,
  PHASE_64_READ_ONLY_SOLANA_PROVIDER_BOUNDARY_VERSION,
  PHASE_64_READ_ONLY_SOLANA_PROVIDER_BOUNDARY_SCHEMA_VERSION,
  READ_ONLY_SOLANA_PROVIDER_BOUNDARY_NAMES,
  READ_ONLY_SOLANA_PROVIDER_BOUNDARY_KINDS,
  READ_ONLY_SOLANA_PROVIDER_BOUNDARY_FIXTURES,
  READ_ONLY_SOLANA_PROVIDER_BOUNDARY_FIXTURE_MAP,
  listReadOnlySolanaProviderBoundaryFixtures,
  getReadOnlySolanaProviderBoundaryFixture,
  buildReadOnlySolanaProviderBoundaryFixture,
  buildReadOnlySolanaMockToRealMapping,
  buildReadOnlySolanaFieldMappingRule,
  buildReadOnlySolanaErrorNormalizationRule,
  buildReadOnlySolanaConformanceCheck,
  buildReadOnlySolanaBoundaryState,
  buildReadOnlySolanaBoundaryReport,
  buildReadOnlySolanaProviderBoundaryViewModel,
  buildReadOnlySolanaProviderBoundaryApiContract,
  selectReadOnlySolanaProviderBoundaryFixture,
  validateReadOnlySolanaProviderBoundaryFixture,
  validateReadOnlySolanaProviderBoundarySafety,
  normalizeReadOnlySolanaProviderBoundaryFixture,
  serializeReadOnlySolanaProviderBoundaryFixture,
  areReadOnlySolanaProviderBoundaryFixturesEqual,
  stableDeterministicReadOnlySolanaProviderBoundaryChecksum,
  getReadOnlySolanaProviderBoundaryCapabilities,
  isValidReadOnlySolanaProviderBoundaryName,
  isValidReadOnlySolanaProviderBoundaryKind,
  isValidReadOnlySolanaProviderBoundaryStateKind,
  isValidReadOnlySolanaProviderBoundaryGeneratedAt,
  isValidReadOnlySolanaProviderBoundarySource,
  isValidReadOnlySolanaProviderBoundarySchemaVersion,
} from './read-only-solana-provider-boundary/index.js';

// ─── Phase 65 — First Real Read-Only Provider Adapter ────────────────────────

export {
  FIRST_READ_ONLY_PROVIDER_ADAPTER_PHASE,
  PHASE_65_FIRST_READ_ONLY_PROVIDER_ADAPTER_GENERATED_AT,
  PHASE_65_FIRST_READ_ONLY_PROVIDER_ADAPTER_SOURCE,
  PHASE_65_FIRST_READ_ONLY_PROVIDER_ADAPTER_VERSION,
  PHASE_65_FIRST_READ_ONLY_PROVIDER_ADAPTER_SCHEMA_VERSION,
  FIRST_READ_ONLY_PROVIDER_ADAPTER_NAMES,
  FIRST_READ_ONLY_PROVIDER_ADAPTER_KINDS,
  FIRST_READ_ONLY_PROVIDER_ADAPTER_FIXTURES,
  FIRST_READ_ONLY_PROVIDER_ADAPTER_FIXTURE_MAP,
  listFirstReadOnlyProviderAdapterFixtures,
  getFirstReadOnlyProviderAdapterFixture,
  buildFirstReadOnlyProviderAdapterFixture,
  buildFirstReadOnlyProviderConfig,
  buildFirstReadOnlyProviderCapabilities,
  buildFirstReadOnlyProviderTransport,
  buildFirstReadOnlyProviderClientContract,
  buildFirstReadOnlyProviderResponseMapping,
  buildFirstReadOnlyProviderErrorNormalization,
  buildFirstReadOnlyProviderConformanceCheck,
  buildFirstReadOnlyProviderHealth,
  buildFirstReadOnlyProviderSmokeGuard,
  buildFirstReadOnlyProviderAdapterReport,
  buildFirstReadOnlyProviderAdapterViewModel,
  buildFirstReadOnlyProviderAdapterApiContract,
  selectFirstReadOnlyProviderAdapterFixture,
  validateFirstReadOnlyProviderAdapterFixture,
  validateFirstReadOnlyProviderAdapterSafety,
  normalizeFirstReadOnlyProviderAdapterFixture,
  serializeFirstReadOnlyProviderAdapterFixture,
  areFirstReadOnlyProviderAdapterFixturesEqual,
  stableDeterministicFirstReadOnlyProviderAdapterChecksum,
  getFirstReadOnlyProviderAdapterCapabilities,
  isValidFirstReadOnlyProviderAdapterName,
  isValidFirstReadOnlyProviderAdapterKind,
  isValidFirstReadOnlyProviderAdapterGeneratedAt,
  isValidFirstReadOnlyProviderAdapterSource,
  isValidFirstReadOnlyProviderAdapterSchemaVersion,
} from './first-read-only-provider-adapter/index.js';

// ─── Phase 66 — Multi-Provider Read-Only Foundation ───────────────────────────

export {
  MULTI_PROVIDER_READ_ONLY_FOUNDATION_PHASE,
  PHASE_66_MULTI_PROVIDER_READ_ONLY_FOUNDATION_GENERATED_AT,
  PHASE_66_MULTI_PROVIDER_READ_ONLY_FOUNDATION_SOURCE,
  PHASE_66_MULTI_PROVIDER_READ_ONLY_FOUNDATION_VERSION,
  PHASE_66_MULTI_PROVIDER_READ_ONLY_FOUNDATION_SCHEMA_VERSION,
  MULTI_PROVIDER_READ_ONLY_FOUNDATION_NAMES,
  MULTI_PROVIDER_READ_ONLY_FOUNDATION_KINDS,
  MULTI_PROVIDER_READ_ONLY_FOUNDATION_FIXTURES,
  MULTI_PROVIDER_READ_ONLY_FOUNDATION_FIXTURE_MAP,
  listMultiProviderReadOnlyFoundationFixtures,
  getMultiProviderReadOnlyFoundationFixture,
  buildMultiProviderReadOnlyFoundationFixture,
  buildMultiProviderRegistry,
  buildMultiProviderNormalizedRecord,
  buildProviderHealthScore,
  buildStaleDataCheck,
  buildReadOnlyFreshnessPolicy,
  buildReadOnlyCachePolicy,
  buildProviderSelectionFixture,
  buildProviderFallbackFixture,
  buildMultiProviderConformanceReport,
  buildMultiProviderReadOnlyFoundationReport,
  buildMultiProviderViewModel,
  buildMultiProviderApiContract,
  selectMultiProviderReadOnlyFoundationFixture,
  validateMultiProviderReadOnlyFoundationFixture,
  validateMultiProviderReadOnlyFoundationSafety,
  normalizeMultiProviderReadOnlyFoundationFixture,
  serializeMultiProviderReadOnlyFoundationFixture,
  areMultiProviderReadOnlyFoundationFixturesEqual,
  stableDeterministicMultiProviderReadOnlyFoundationChecksum,
  getMultiProviderReadOnlyFoundationCapabilities,
  isValidMultiProviderReadOnlyFoundationName,
  isValidMultiProviderReadOnlyFoundationKind,
  isValidMultiProviderReadOnlyFoundationGeneratedAt,
  isValidMultiProviderReadOnlyFoundationSource,
  isValidMultiProviderReadOnlyFoundationSchemaVersion,
} from './multi-provider-read-only-foundation/index.js';

// ─── Phase 67 — Cross-Provider Data Quality and Reconciliation ────────────────

export {
  CROSS_PROVIDER_DATA_QUALITY_PHASE,
  PHASE_67_CROSS_PROVIDER_DATA_QUALITY_GENERATED_AT,
  PHASE_67_CROSS_PROVIDER_DATA_QUALITY_SOURCE,
  PHASE_67_CROSS_PROVIDER_DATA_QUALITY_VERSION,
  PHASE_67_CROSS_PROVIDER_DATA_QUALITY_SCHEMA_VERSION,
  CROSS_PROVIDER_DATA_QUALITY_NAMES,
  CROSS_PROVIDER_DATA_QUALITY_KINDS,
  CROSS_PROVIDER_DATA_QUALITY_FIXTURES,
  CROSS_PROVIDER_DATA_QUALITY_FIXTURE_MAP,
  listCrossProviderDataQualityFixtures,
  getCrossProviderDataQualityFixture,
  buildCrossProviderDataQualityFixture,
  buildProviderDataQualityIssue,
  buildProviderComparison,
  buildProviderMismatchReport,
  buildProviderReconciliationPolicy,
  buildProviderReconciliationResult,
  buildProviderConfidenceScore,
  buildProviderProvenanceRecord,
  buildReadOnlyProviderEnrichmentContract,
  buildCrossProviderDataQualityReport,
  buildCrossProviderDataQualityViewModel,
  buildCrossProviderDataQualityApiContract,
  selectCrossProviderDataQualityFixture,
  validateCrossProviderDataQualityFixture,
  validateCrossProviderDataQualitySafety,
  normalizeCrossProviderDataQualityFixture,
  serializeCrossProviderDataQualityFixture,
  areCrossProviderDataQualityFixturesEqual,
  getCrossProviderDataQualityCapabilities,
  stableDeterministicCrossProviderDataQualityChecksum,
  isValidCrossProviderDataQualityName,
  isValidCrossProviderDataQualityKind,
  isValidCrossProviderDataQualityGeneratedAt,
  isValidCrossProviderDataQualitySource,
  isValidCrossProviderDataQualitySchemaVersion,
} from './cross-provider-data-quality/index.js';

// ─── Phase 68 — Provider-Aware Replay and Scenario Generation ─────────────────

export {
  PROVIDER_AWARE_REPLAY_SCENARIOS_PHASE,
  PHASE_68_PROVIDER_AWARE_REPLAY_SCENARIOS_GENERATED_AT,
  PHASE_68_PROVIDER_AWARE_REPLAY_SCENARIOS_SOURCE,
  PHASE_68_PROVIDER_AWARE_REPLAY_SCENARIOS_VERSION,
  PHASE_68_PROVIDER_AWARE_REPLAY_SCENARIOS_SCHEMA_VERSION,
  PROVIDER_AWARE_REPLAY_SCENARIO_NAMES,
  PROVIDER_AWARE_REPLAY_SCENARIO_KINDS,
  PROVIDER_AWARE_REPLAY_SCENARIO_FIXTURES,
  PROVIDER_AWARE_REPLAY_SCENARIO_FIXTURE_MAP,
  listProviderAwareReplayScenarioFixtures,
  getProviderAwareReplayScenarioFixture,
  buildProviderAwareReplayScenarioFixture,
  buildProviderAwareReplayImport,
  buildProviderAwareReplayScenario,
  buildProviderReplayProvenanceMapping,
  buildProviderReplayParityCheck,
  buildProviderFixtureRegenerationContract,
  buildProviderObservationReplayReport,
  buildGeneratedLifecyclePreview,
  buildReplayExpectationModel,
  buildProviderAwareReplayViewModel,
  buildProviderAwareReplayApiContract,
  selectProviderAwareReplayScenarioFixture,
  validateProviderAwareReplayScenarioFixture,
  validateProviderAwareReplayScenarioSafety,
  normalizeProviderAwareReplayScenarioFixture,
  serializeProviderAwareReplayScenarioFixture,
  areProviderAwareReplayScenarioFixturesEqual,
  getProviderAwareReplayScenarioCapabilities,
  stableDeterministicProviderAwareReplayScenarioChecksum,
  isValidProviderAwareReplayScenarioName,
  isValidProviderAwareReplayScenarioKind,
  isValidProviderAwareReplayScenarioGeneratedAt,
  isValidProviderAwareReplayScenarioSource,
  isValidProviderAwareReplayScenarioSchemaVersion,
} from './provider-aware-replay-scenarios/index.js';

// ─── Phase 69 — Live Smoke Harness Expansion and Safety Certification ───────────

export {
  LIVE_SMOKE_SAFETY_CERTIFICATION_PHASE,
  PHASE_69_LIVE_SMOKE_SAFETY_CERTIFICATION_GENERATED_AT,
  PHASE_69_LIVE_SMOKE_SAFETY_CERTIFICATION_SOURCE,
  PHASE_69_LIVE_SMOKE_SAFETY_CERTIFICATION_VERSION,
  PHASE_69_LIVE_SMOKE_SAFETY_CERTIFICATION_SCHEMA_VERSION,
  LIVE_SMOKE_SAFETY_CERTIFICATION_NAMES,
  LIVE_SMOKE_SAFETY_CERTIFICATION_KINDS,
  LIVE_SMOKE_SAFETY_CERTIFICATION_FIXTURES,
  LIVE_SMOKE_SAFETY_CERTIFICATION_FIXTURE_MAP,
  listLiveSmokeSafetyCertificationFixtures,
  getLiveSmokeSafetyCertificationFixture,
  buildLiveSmokeSafetyCertificationFixture,
  buildLiveSmokeConfig,
  buildSmokeGuardPolicy,
  buildSmokePlan,
  buildReadOnlySmokeCheck,
  buildProviderSmokeEligibilityCheck,
  buildNetworkIsolationPolicy,
  buildSmokeResult,
  buildProviderCertificationGate,
  buildSafetyCertificate,
  buildOfflineCiCertificationContract,
  buildLiveSmokeCertificationReport,
  buildLiveSmokeSafetyViewModel,
  buildLiveSmokeSafetyApiContract,
  selectLiveSmokeSafetyCertificationFixture,
  validateLiveSmokeSafetyCertificationFixture,
  validateLiveSmokeSafetyCertificationSafety,
  normalizeLiveSmokeSafetyCertificationFixture,
  serializeLiveSmokeSafetyCertificationFixture,
  areLiveSmokeSafetyCertificationFixturesEqual,
  getLiveSmokeSafetyCertificationCapabilities,
  stableDeterministicLiveSmokeSafetyCertificationChecksum,
  isValidLiveSmokeSafetyCertificationName,
  isValidLiveSmokeSafetyCertificationKind,
  isValidLiveSmokeSafetyCertificationGeneratedAt,
  isValidLiveSmokeSafetyCertificationSource,
  isValidLiveSmokeSafetyCertificationSchemaVersion,
} from './live-smoke-safety-certification/index.js';

// ─── Phase 70 — Provider Reliability Telemetry and Drift Audit ─────────────────

export {
  PROVIDER_RELIABILITY_DRIFT_AUDIT_PHASE,
  PHASE_70_PROVIDER_RELIABILITY_DRIFT_AUDIT_GENERATED_AT,
  PHASE_70_PROVIDER_RELIABILITY_DRIFT_AUDIT_SOURCE,
  PHASE_70_PROVIDER_RELIABILITY_DRIFT_AUDIT_VERSION,
  PHASE_70_PROVIDER_RELIABILITY_DRIFT_AUDIT_SCHEMA_VERSION,
  PROVIDER_RELIABILITY_DRIFT_AUDIT_NAMES,
  PROVIDER_RELIABILITY_DRIFT_AUDIT_KINDS,
  PROVIDER_RELIABILITY_DRIFT_AUDIT_FIXTURES,
  PROVIDER_RELIABILITY_DRIFT_AUDIT_FIXTURE_MAP,
  listProviderReliabilityDriftAuditFixtures,
  getProviderReliabilityDriftAuditFixture,
  buildProviderReliabilityDriftAuditFixture,
  buildProviderTelemetrySample,
  buildProviderFreshnessModel,
  buildProviderReliabilityScore,
  buildProviderDriftAudit,
  buildProviderSchemaDrift,
  buildProviderConfidenceTrend,
  buildProviderInstabilityEvent,
  buildProviderStaleDataAudit,
  buildProviderConformanceDrift,
  buildProviderCertificationTelemetryLinkage,
  buildProviderReplayDriftLinkage,
  buildProviderReliabilityReport,
  buildProviderReliabilityViewModel,
  buildProviderReliabilityApiContract,
  selectProviderReliabilityDriftAuditFixture,
  validateProviderReliabilityDriftAuditFixture,
  validateProviderReliabilityDriftAuditSafety,
  normalizeProviderReliabilityDriftAuditFixture,
  serializeProviderReliabilityDriftAuditFixture,
  areProviderReliabilityDriftAuditFixturesEqual,
  getProviderReliabilityDriftAuditCapabilities,
  stableDeterministicProviderReliabilityDriftAuditChecksum,
  isValidProviderReliabilityDriftAuditName,
  isValidProviderReliabilityDriftAuditKind,
  isValidProviderReliabilityDriftAuditGeneratedAt,
  isValidProviderReliabilityDriftAuditSource,
  isValidProviderReliabilityDriftAuditSchemaVersion,
} from './provider-reliability-drift-audit/index.js';

// ─── Phase 71 — Read-Only Historical Snapshot Ingestion Contracts ─────────────

export {
  HISTORICAL_SNAPSHOT_INGESTION_CONTRACTS_PHASE,
  PHASE_71_HISTORICAL_SNAPSHOT_INGESTION_CONTRACTS_GENERATED_AT,
  PHASE_71_HISTORICAL_SNAPSHOT_INGESTION_CONTRACTS_SOURCE,
  PHASE_71_HISTORICAL_SNAPSHOT_INGESTION_CONTRACTS_VERSION,
  PHASE_71_HISTORICAL_SNAPSHOT_INGESTION_CONTRACTS_SCHEMA_VERSION,
  HISTORICAL_SNAPSHOT_INGESTION_CONTRACT_NAMES,
  HISTORICAL_SNAPSHOT_INGESTION_CONTRACT_KINDS,
  HISTORICAL_SNAPSHOT_INGESTION_CONTRACT_FIXTURES,
  HISTORICAL_SNAPSHOT_INGESTION_CONTRACT_FIXTURE_MAP,
  listHistoricalSnapshotIngestionContractFixtures,
  getHistoricalSnapshotIngestionContractFixture,
  buildHistoricalSnapshotIngestionContractFixture,
  buildSnapshotManifest,
  buildSnapshotSourceMetadata,
  buildSnapshotSchemaContract,
  buildSnapshotProvenanceContract,
  buildSnapshotNormalizationContract,
  buildSnapshotValidationContract,
  buildSnapshotFreshnessContract,
  buildSnapshotIntegrityContract,
  buildSnapshotImportPlan,
  buildSnapshotRejectionContract,
  buildSnapshotReplayLinkage,
  buildSnapshotReliabilityLinkage,
  buildHistoricalSnapshotAuditReport,
  buildHistoricalSnapshotViewModel,
  buildHistoricalSnapshotApiContract,
  selectHistoricalSnapshotIngestionContractFixture,
  validateHistoricalSnapshotIngestionContractFixture,
  validateHistoricalSnapshotIngestionContractSafety,
  normalizeHistoricalSnapshotIngestionContractFixture,
  serializeHistoricalSnapshotIngestionContractFixture,
  areHistoricalSnapshotIngestionContractFixturesEqual,
  getHistoricalSnapshotIngestionContractCapabilities,
  stableDeterministicHistoricalSnapshotIngestionContractChecksum,
  isValidHistoricalSnapshotIngestionContractName,
  isValidHistoricalSnapshotIngestionContractKind,
  isValidHistoricalSnapshotIngestionContractGeneratedAt,
  isValidHistoricalSnapshotIngestionContractSource,
  isValidHistoricalSnapshotIngestionContractSchemaVersion,
} from './historical-snapshot-ingestion-contracts/index.js';

// ─── Phase 72 — Deterministic Snapshot Scenario Generator ──────────────────────

export {
  HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_PHASE,
  PHASE_72_HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_GENERATED_AT,
  PHASE_72_HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_SOURCE,
  PHASE_72_HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_VERSION,
  PHASE_72_HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_SCHEMA_VERSION,
  HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_NAMES,
  HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_KINDS,
  HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_FIXTURES,
  HISTORICAL_SNAPSHOT_SCENARIO_GENERATOR_FIXTURE_MAP,
  listHistoricalSnapshotScenarioGeneratorFixtures,
  getHistoricalSnapshotScenarioGeneratorFixture,
  buildHistoricalSnapshotScenarioGeneratorFixture,
  buildHistoricalSnapshotGenerationPlan,
  buildSnapshotSourceSelection,
  buildGeneratedScenarioDescriptor,
  buildSnapshotReplayDescriptor,
  buildSnapshotScenarioLineage,
  buildSnapshotScenarioIntegrityContract,
  buildSnapshotScenarioValidationContract,
  buildSnapshotScenarioRejectionContract,
  buildSnapshotScenarioQualityLinkage,
  buildSnapshotScenarioReliabilityLinkage,
  buildSnapshotScenarioRiskLinkage,
  buildSnapshotScenarioGenerationRules,
  buildSnapshotScenarioAuditReport,
  buildSnapshotScenarioViewModel,
  buildSnapshotScenarioApiContract,
  selectHistoricalSnapshotScenarioGeneratorFixture,
  validateHistoricalSnapshotScenarioGeneratorFixture,
  validateHistoricalSnapshotScenarioGeneratorSafety,
  normalizeHistoricalSnapshotScenarioGeneratorFixture,
  serializeHistoricalSnapshotScenarioGeneratorFixture,
  areHistoricalSnapshotScenarioGeneratorFixturesEqual,
  getHistoricalSnapshotScenarioGeneratorCapabilities,
  stableDeterministicHistoricalSnapshotScenarioGeneratorChecksum,
  isValidHistoricalSnapshotScenarioGeneratorName,
  isValidHistoricalSnapshotScenarioGeneratorKind,
  isValidHistoricalSnapshotScenarioGeneratorGeneratedAt,
  isValidHistoricalSnapshotScenarioGeneratorSource,
  isValidHistoricalSnapshotScenarioGeneratorSchemaVersion,
} from './historical-snapshot-scenario-generator/index.js';

// ─── Phase 73 — Optional Provider-Aware Replay Import Contracts ───────────────

export {
  PROVIDER_AWARE_REPLAY_IMPORT_CONTRACTS_PHASE,
  PHASE_73_PROVIDER_AWARE_REPLAY_IMPORT_CONTRACTS_GENERATED_AT,
  PHASE_73_PROVIDER_AWARE_REPLAY_IMPORT_CONTRACTS_SOURCE,
  PHASE_73_PROVIDER_AWARE_REPLAY_IMPORT_CONTRACTS_VERSION,
  PHASE_73_PROVIDER_AWARE_REPLAY_IMPORT_CONTRACTS_SCHEMA_VERSION,
  PROVIDER_AWARE_REPLAY_IMPORT_CONTRACT_NAMES,
  PROVIDER_AWARE_REPLAY_IMPORT_CONTRACT_KINDS,
  PROVIDER_AWARE_REPLAY_IMPORT_CONTRACT_FIXTURES,
  PROVIDER_AWARE_REPLAY_IMPORT_CONTRACT_FIXTURE_MAP,
  listProviderAwareReplayImportContractFixtures,
  getProviderAwareReplayImportContractFixture,
  buildProviderAwareReplayImportContractFixture,
  buildReplayImportCandidate,
  buildReplayImportManifest,
  buildReplayImportSourceMetadata,
  buildReplayImportCompatibilityContract,
  buildReplayImportGatePolicy,
  buildReplayImportPlan,
  buildReplayImportRejectionContract,
  buildReplayImportNormalizationContract,
  buildReplayImportValidationContract,
  buildReplayImportIntegrityContract,
  buildReplayImportProvenanceContract,
  buildReplayImportScenarioLinkage,
  buildReplayImportSnapshotLinkage,
  buildReplayImportReliabilityLinkage,
  buildReplayImportQualityLinkage,
  buildReplayImportAuditReport,
  buildReplayImportViewModel,
  buildReplayImportApiContract,
  selectProviderAwareReplayImportContractFixture,
  validateProviderAwareReplayImportContractFixture,
  validateProviderAwareReplayImportContractSafety,
  normalizeProviderAwareReplayImportContractFixture,
  serializeProviderAwareReplayImportContractFixture,
  areProviderAwareReplayImportContractFixturesEqual,
  stableDeterministicProviderAwareReplayImportContractChecksum,
  getProviderAwareReplayImportContractCapabilities,
  isValidProviderAwareReplayImportContractName,
  isValidProviderAwareReplayImportContractKind,
  isValidProviderAwareReplayImportContractGeneratedAt,
  isValidProviderAwareReplayImportContractSource,
  isValidProviderAwareReplayImportContractSchemaVersion,
} from './provider-aware-replay-import-contracts/index.js';
