import type { ProviderReliabilityDriftAuditCapabilities } from './types.js';

export function getProviderReliabilityDriftAuditCapabilities(): ProviderReliabilityDriftAuditCapabilities {
  return {
    providerReliabilityDriftAudit: true,
    deterministicProviderTelemetryModels: true,
    fixtureDerivedProviderReliability: true,
    providerFreshnessModels: true,
    providerStaleDataAudits: true,
    providerReliabilityScoring: true,
    providerDriftDetection: true,
    providerSchemaDriftAudits: true,
    providerConformanceDriftAudits: true,
    providerInstabilityEvents: true,
    providerCertificationTelemetryLinkage: true,
    providerReplayDriftLinkage: true,
    providerReliabilityReports: true,
    providerReliabilityViewModels: true,
    providerReliabilityApiContracts: true,
    providerReliabilitySelectors: true,
    providerReliabilityLiveTelemetry: false,
    providerReliabilityLiveNetworkAccess: false,
    providerReliabilityRuntimeMonitoring: false,
    providerReliabilitySecretsRequired: false,
    providerReliabilityApiKeyRequired: false,
    providerReliabilityWriteMethods: false,
    providerReliabilityWalletLogic: false,
    providerReliabilityPrivateKeyHandling: false,
    providerReliabilitySigning: false,
    providerReliabilityTransactionSending: false,
    providerReliabilityExecution: false,
    providerReliabilityTradingSignals: false,
    providerReliabilityRecommendations: false,
    providerReliabilityInvestmentAdvice: false,
    providerReliabilityRouteHandlers: false,
    providerReliabilityRuntimeRequests: false,
    providerReliabilityUiRendering: false,
    providerReliabilityDomAccess: false,
    providerReliabilityPersistence: false,
    providerReliabilityFilesystemWrites: false,
    providerReliabilityBackgroundJobs: false,
    providerReliabilityScheduledJobs: false,
    providerReliabilityRealOrders: false,
    providerReliabilityRealFunds: false,
    providerReliabilityRealPnL: false,
    providerReliabilityAutoExecution: false,
    providerReliabilityProviderExpansion: false,
  };
}
