import type { LiveSmokeSafetyCertificationCapabilities } from './types.js';

export function getLiveSmokeSafetyCertificationCapabilities(): LiveSmokeSafetyCertificationCapabilities {
  return {
    liveSmokeSafetyCertification: true,
    deterministicSmokeHarnessModels: true,
    disabledByDefaultSmokeGuards: true,
    readOnlySmokeCheckContracts: true,
    providerSmokeEligibilityChecks: true,
    networkIsolationPolicies: true,
    smokeResultModels: true,
    safetyCertificationReports: true,
    offlineCiCertificationContracts: true,
    liveSmokeSafetyViewModels: true,
    liveSmokeSafetyApiContracts: true,
    liveSmokeSafetySelectors: true,
    fixtureDerivedSmokeCertification: true,
    localOnlySmokeCertificationDefaults: true,
    liveSmokeStandardCiNetworkAccess: false,
    liveSmokeDefaultNetworkAccess: false,
    liveSmokeSecretsRequired: false,
    liveSmokeApiKeyRequired: false,
    liveSmokeWriteMethods: false,
    liveSmokeWalletLogic: false,
    liveSmokePrivateKeyHandling: false,
    liveSmokeSigning: false,
    liveSmokeTransactionSending: false,
    liveSmokeExecution: false,
    liveSmokeTradingSignals: false,
    liveSmokeRecommendations: false,
    liveSmokeInvestmentAdvice: false,
    liveSmokeRouteHandlers: false,
    liveSmokeRuntimeRequests: false,
    liveSmokeUiRendering: false,
    liveSmokeDomAccess: false,
    liveSmokePersistence: false,
    liveSmokeFilesystemWrites: false,
    liveSmokeBackgroundJobs: false,
    liveSmokeScheduledJobs: false,
    liveSmokeRealOrders: false,
    liveSmokeRealFunds: false,
    liveSmokeRealPnL: false,
    liveSmokeAutoExecution: false,
    liveSmokeProviderExpansion: false,
    liveSmokeLiveReconciliation: false,
    liveSmokeLiveReplayImport: false,
  };
}
