import type { ReadOnlySolanaProviderBoundaryCapabilities } from './types.js';

export function getReadOnlySolanaProviderBoundaryCapabilities(): ReadOnlySolanaProviderBoundaryCapabilities {
  return {
    readOnlySolanaProviderBoundary: true,
    readOnlySolanaProviderBoundaryFixtures: true,
    deterministicReadOnlySolanaProviderBoundary: true,
    localOnlyReadOnlySolanaProviderBoundary: true,
    fixtureDerivedReadOnlySolanaProviderBoundary: true,
    readOnlySolanaMockToRealMappings: true,
    readOnlySolanaFieldMappingRules: true,
    readOnlySolanaErrorNormalizationRules: true,
    readOnlySolanaConformanceChecks: true,
    readOnlySolanaBoundaryReports: true,
    readOnlySolanaBoundaryViewModels: true,
    readOnlySolanaBoundaryApiContracts: true,
    readOnlySolanaBoundarySelectors: true,
    readOnlySolanaBoundaryLiveData: false,
    readOnlySolanaBoundaryNetworkAccess: false,
    readOnlySolanaBoundaryRealProviders: false,
    readOnlySolanaBoundaryProviderAdapters: false,
    readOnlySolanaBoundaryProviderSdk: false,
    readOnlySolanaBoundaryApiKeys: false,
    readOnlySolanaBoundarySolanaRpc: false,
    readOnlySolanaBoundaryWebSocketAccess: false,
    readOnlySolanaBoundaryGeyserYellowstone: false,
    readOnlySolanaBoundaryPumpFunIntegration: false,
    readOnlySolanaBoundaryDexIntegration: false,
    readOnlySolanaBoundaryJitoIntegration: false,
    readOnlySolanaBoundaryPersistence: false,
    readOnlySolanaBoundaryFilesystemWrites: false,
    readOnlySolanaBoundaryDownloads: false,
    readOnlySolanaBoundaryRouteHandlers: false,
    readOnlySolanaBoundaryHttpServer: false,
    readOnlySolanaBoundaryRuntimeRequests: false,
    readOnlySolanaBoundaryUiRendering: false,
    readOnlySolanaBoundaryDomAccess: false,
    readOnlySolanaBoundaryBackgroundJobs: false,
    readOnlySolanaBoundaryScheduledJobs: false,
    readOnlySolanaBoundaryWalletLogic: false,
    readOnlySolanaBoundaryPrivateKeyHandling: false,
    readOnlySolanaBoundarySigning: false,
    readOnlySolanaBoundaryTransactionSending: false,
    readOnlySolanaBoundaryExecution: false,
    readOnlySolanaBoundaryTradingSignals: false,
    readOnlySolanaBoundaryRecommendations: false,
    readOnlySolanaBoundaryInvestmentAdvice: false,
    readOnlySolanaBoundaryLiveExecution: false,
    readOnlySolanaBoundaryStrategySelection: false,
    readOnlySolanaBoundaryRealOrders: false,
    readOnlySolanaBoundaryRealFunds: false,
    readOnlySolanaBoundaryRealPnL: false,
    readOnlySolanaBoundaryWriteCapabilities: false,
  };
}

