import type { ReadOnlyProviderAdapterGateCapabilities } from './types.js';

export function getReadOnlyProviderAdapterGateCapabilities(): ReadOnlyProviderAdapterGateCapabilities {
  return {
    readOnlyProviderAdapterGate: true,
    readOnlyProviderAdapterGateFixtures: true,
    deterministicReadOnlyProviderAdapterGate: true,
    localOnlyReadOnlyProviderAdapterGate: true,
    fixtureDerivedReadOnlyProviderAdapterGate: true,
    failClosedReadOnlyProviderAdapterGate: true,
    readOnlyProviderGatePolicies: true,
    readOnlyProviderGateStates: true,
    readOnlyProviderResolutionFixtures: true,
    readOnlyProviderCapabilityChecks: true,
    readOnlyProviderCompatibilityChecks: true,
    readOnlyProviderGateReports: true,
    readOnlyProviderGateViewModels: true,
    readOnlyProviderGateApiContracts: true,
    readOnlyProviderGateSelectors: true,
    readOnlyProviderGateLiveData: false,
    readOnlyProviderGateNetworkAccess: false,
    readOnlyProviderGateRealProviders: false,
    readOnlyProviderGateProviderAdapters: false,
    readOnlyProviderGateSolanaRpc: false,
    readOnlyProviderGateWebSocketAccess: false,
    readOnlyProviderGateGeyserYellowstone: false,
    readOnlyProviderGatePumpFunIntegration: false,
    readOnlyProviderGateDexIntegration: false,
    readOnlyProviderGateJitoIntegration: false,
    readOnlyProviderGatePersistence: false,
    readOnlyProviderGateFilesystemWrites: false,
    readOnlyProviderGateDownloads: false,
    readOnlyProviderGateRouteHandlers: false,
    readOnlyProviderGateHttpServer: false,
    readOnlyProviderGateRuntimeRequests: false,
    readOnlyProviderGateUiRendering: false,
    readOnlyProviderGateDomAccess: false,
    readOnlyProviderGateBackgroundJobs: false,
    readOnlyProviderGateScheduledJobs: false,
    readOnlyProviderGateWalletLogic: false,
    readOnlyProviderGatePrivateKeyHandling: false,
    readOnlyProviderGateSigning: false,
    readOnlyProviderGateTransactionSending: false,
    readOnlyProviderGateExecution: false,
    readOnlyProviderGateTradingSignals: false,
    readOnlyProviderGateRecommendations: false,
    readOnlyProviderGateInvestmentAdvice: false,
    readOnlyProviderGateLiveExecution: false,
    readOnlyProviderGateStrategySelection: false,
    readOnlyProviderGateRealOrders: false,
    readOnlyProviderGateRealFunds: false,
    readOnlyProviderGateRealPnL: false,
  };
}
